// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Loading' | 'Disabled' | 'Success' | 'Error' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-MMET2FZU";
import { routes } from "./chunks/chunk-VG7AXKTA";

// virtual:button-form
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/guPbXM49b32WDPBebU3p/fQr5csclaUCy01VNBND4/yiH6vmYhG.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var ArrowRightFonts = getFonts(stdin_default);
var MotionDivWithFX = withFX(motion.div);
var enabledGestures = {
	NVntRrOqh: {
		hover: true,
	},
};
var cycleOrder = [
	"NVntRrOqh",
	"XtPtZdCg0",
	"khDz2CmGT",
	"FLsCQX_8c",
	"qh2s31TM3",
];
var serializationHash = "framer-6Zz3t";
var variantClassNames = {
	FLsCQX_8c: "framer-v-1l6re0t",
	khDz2CmGT: "framer-v-1qnsi92",
	NVntRrOqh: "framer-v-1spz190",
	qh2s31TM3: "framer-v-1kx6kn0",
	XtPtZdCg0: "framer-v-4vvksw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.2,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 1,
	ease: [0, 0, 1, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 360,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Default: "NVntRrOqh",
	Disabled: "khDz2CmGT",
	Error: "qh2s31TM3",
	Loading: "XtPtZdCg0",
	Success: "FLsCQX_8c",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "NVntRrOqh",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "NVntRrOqh",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "XtPtZdCg0") return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "XtPtZdCg0") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.button
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1spz190",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						data-reset={"button"}
						layoutDependency={layoutDependency}
						layoutId={"NVntRrOqh"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
							borderBottomLeftRadius: "50%",
							borderBottomRightRadius: "50%",
							borderTopLeftRadius: "50%",
							borderTopRightRadius: "50%",
							opacity: 1,
							...style,
						}}
						variants={{
							"NVntRrOqh-hover": {
								opacity: 0.5,
							},
							FLsCQX_8c: {
								backgroundColor: "rgb(0, 0, 0)",
								opacity: 1,
							},
							khDz2CmGT: {
								opacity: 0.5,
							},
							qh2s31TM3: {
								backgroundColor: "rgb(255, 0, 0)",
								opacity: 1,
							},
						}}
						{...addPropertyOverrides(
							{
								"NVntRrOqh-hover": {
									"data-framer-name": void 0,
								},
								FLsCQX_8c: {
									"data-framer-name": "Success",
								},
								khDz2CmGT: {
									"data-framer-name": "Disabled",
								},
								qh2s31TM3: {
									"data-framer-name": "Error",
								},
								XtPtZdCg0: {
									"data-framer-name": "Loading",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{isDisplayed() &&
							_jsx(stdin_default, {
								animated: true,
								className: "framer-7cq06g",
								layoutDependency,
								layoutId: "GdydMPbu9",
								style: {
									"--1m973uw":
										"var(--token-e27a4cac-2b4d-4ad5-8c68-b6f48982239d, rgb(249, 245, 246))",
									"--js9iwy": 2,
								},
								variants: {
									FLsCQX_8c: {
										"--1m973uw": "rgba(249, 245, 246, 0.5)",
									},
								},
							})}
						{isDisplayed1() && (
							<motion.div
								className={"framer-1eq4phc"}
								data-framer-name={"Spinner"}
								layoutDependency={layoutDependency}
								layoutId={"iCYXSBY2K"}
								style={{
									mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
									WebkitMask:
										"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
								}}
							>
								<MotionDivWithFX
									__framer__loop={animation}
									__framer__loopEffectEnabled={true}
									__framer__loopRepeatDelay={0}
									__framer__loopRepeatType={"loop"}
									__framer__loopTransition={transition2}
									__perspectiveFX={false}
									__smartComponentFX={true}
									__targetOpacity={1}
									className={"framer-1yiqet8"}
									data-framer-name={"Conic"}
									layoutDependency={layoutDependency}
									layoutId={"XawAV60dD"}
									style={{
										background:
											"conic-gradient(from 180deg at 50% 50%, rgb(68, 204, 255) 0deg, rgb(68, 204, 255) 360deg)",
										backgroundColor: "rgb(68, 204, 255)",
										mask: "none",
										WebkitMask: "none",
									}}
									variants={{
										XtPtZdCg0: {
											background:
												"conic-gradient(from 0deg at 50% 50%, rgba(255, 255, 255, 0) 7.208614864864882deg, rgb(255, 255, 255) 342deg)",
											backgroundColor: "rgba(0, 0, 0, 0)",
											mask: "url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
											WebkitMask:
												"url('https://framerusercontent.com/images/pGiXYozQ3mE4cilNOItfe2L2fUA.svg?width=20&height=20') alpha no-repeat center / cover add",
										},
									}}
								>
									<motion.div
										className={"framer-14qihjq"}
										data-framer-name={"Rounding"}
										layoutDependency={layoutDependency}
										layoutId={"sGyRx_JH3"}
										style={{
											backgroundColor: "rgb(255, 255, 255)",
											borderBottomLeftRadius: 1,
											borderBottomRightRadius: 1,
											borderTopLeftRadius: 1,
											borderTopRightRadius: 1,
										}}
										transformTemplate={transformTemplate1}
									/>
								</MotionDivWithFX>
							</motion.div>
						)}
					</motion.button>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-6Zz3t.framer-vl5e9z, .framer-6Zz3t .framer-vl5e9z { display: block; }",
	".framer-6Zz3t.framer-1spz190 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 40px; }",
	".framer-6Zz3t .framer-7cq06g { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 24px); position: relative; width: 24px; }",
	".framer-6Zz3t .framer-1eq4phc { aspect-ratio: 1 / 1; flex: none; gap: 10px; height: var(--framer-aspect-ratio-supported, 20px); overflow: hidden; position: relative; width: 16px; }",
	".framer-6Zz3t .framer-1yiqet8 { bottom: 0px; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-6Zz3t .framer-14qihjq { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 2px); left: 50%; overflow: visible; position: absolute; top: 0px; width: 2px; }",
	".framer-6Zz3t.framer-v-4vvksw.framer-1spz190, .framer-6Zz3t.framer-v-1qnsi92.framer-1spz190, .framer-6Zz3t.framer-v-1l6re0t.framer-1spz190, .framer-6Zz3t.framer-v-1kx6kn0.framer-1spz190 { cursor: unset; }",
	".framer-6Zz3t.framer-v-4vvksw .framer-1eq4phc { height: var(--framer-aspect-ratio-supported, 16px); }",
	".framer-6Zz3t.framer-v-4vvksw .framer-1yiqet8 { overflow: hidden; }",
];
var FrameryiH6vmYhG = withCSS(Component, css, "framer-6Zz3t");
var stdin_default2 = FrameryiH6vmYhG;
FrameryiH6vmYhG.displayName = "Button Form";
FrameryiH6vmYhG.defaultProps = {
	height: 40,
	width: 40,
};
addPropertyControls(FrameryiH6vmYhG, {
	variant: {
		options: ["NVntRrOqh", "XtPtZdCg0", "khDz2CmGT", "FLsCQX_8c", "qh2s31TM3"],
		optionTitles: ["Default", "Loading", "Disabled", "Success", "Error"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameryiH6vmYhG,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ArrowRightFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button-form
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale = "", ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var button_form_default = ComponentWithRoot;
export { button_form_default as default };
