// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * loginLink?: string // Login Link
}} Props

 */
import { routes } from "./chunks/chunk-VG7AXKTA";

// virtual:signup-form
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ODDARncIaHoqa28zs3yX/9DZC1Mp1vfYwcfdgNLNM/SignupForm.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addPropertyControls, ControlType } from "unframer";
import { useState } from "react";
import { colors } from "../lib/colors";
var fontFamily = `"Epilogue", sans-serif`;
var primaryButton = {
	display: "flex",
	alignItems: "center",
	justifyContent: "center",
	backgroundColor: colors.primary,
	border: `2px solid ${colors.black}`,
	borderRadius: "12px",
	padding: "12px 16px",
	boxShadow: `4px 4px 0px 0px ${colors.black}`,
	fontFamily,
	fontWeight: 700,
	fontSize: "16px",
	lineHeight: "1.5em",
	letterSpacing: "-0.04em",
	color: colors.white,
	cursor: "pointer",
	transition: "box-shadow 0.2s ease, transform 0.2s ease",
	textAlign: "center",
	boxSizing: "border-box",
	userSelect: "none",
};
var inputWrapper = {
	width: "100%",
	height: 48,
	backgroundColor: colors.white,
	borderRadius: 12,
	border: `2px solid ${colors.black}`,
	boxShadow: `2px 2px 0px 0px ${colors.black}`,
	display: "flex",
	alignItems: "center",
	padding: "0 18px",
	boxSizing: "border-box",
	overflow: "hidden",
	transition: "box-shadow 0.2s",
};
var inputInner = {
	width: "100%",
	height: "100%",
	border: "none",
	background: "transparent",
	outline: "none",
	fontFamily,
	fontWeight: 500,
	fontSize: 16,
	lineHeight: "1.2",
	letterSpacing: "-0.04em",
	color: colors.black,
	padding: 0,
	margin: 0,
	appearance: "none",
	WebkitAppearance: "none",
};
function InputField({ type = "text", placeholder, value, onChange }) {
	const [focused, setFocused] = useState(false);
	return (
		<div
			style={{
				...inputWrapper,
				boxShadow: focused ? `0 0 0 2px ${colors.accent}` : "none",
			}}
		>
			<input
				type={type}
				placeholder={placeholder}
				value={value}
				onChange={onChange}
				onFocus={() => setFocused(true)}
				onBlur={() => setFocused(false)}
				className={"reef-input-inner"}
				style={inputInner}
			/>
		</div>
	);
}
function GoogleIcon() {
	return (
		<svg width={"20"} height={"20"} viewBox={"0 0 48 48"}>
			<path
				fill={"#EA4335"}
				d={
					"M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"
				}
			/>
			<path
				fill={"#4285F4"}
				d={
					"M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"
				}
			/>
			<path
				fill={"#FBBC05"}
				d={
					"M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"
				}
			/>
			<path
				fill={"#34A853"}
				d={
					"M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"
				}
			/>
		</svg>
	);
}
function AppleIcon() {
	return (
		<svg width={"20"} height={"20"} viewBox={"0 0 814 1000"}>
			<path
				d={
					"M788.1 340.9c-5.8 4.5-108.2 62.2-108.2 190.5 0 148.4 130.3 200.9 134.2 202.2-.6 3.2-20.7 71.9-68.7 141.9-42.8 61.6-87.5 123.1-155.5 123.1s-85.5-39.5-164-39.5c-76.5 0-103.7 40.8-165.9 40.8s-105.6-57.8-155.5-127.4c-58.3-81.2-105.3-207.6-105.3-328.3 0-193 125.3-295.3 248.3-295.3 65.5 0 120.1 43.1 161.2 43.1 39.2 0 100.4-45.8 174.7-45.8 28.2 0 129.6 2.6 196.6 99.8zM554.1 159.4c31.1-36.9 53.1-88.1 53.1-139.3 0-7.1-.6-14.3-1.9-20.1-50.6 1.9-110.8 33.7-147.1 75.8-28.8 32.4-54.1 83.6-54.1 135.5 0 7.8 1.3 15.6 1.9 18.1 3.2.6 8.4 1.3 13.6 1.3 45.4 0 102.5-30.4 134.5-71.3z"
				}
			/>
		</svg>
	);
}
function SignupForm(props) {
	const { loginLink = "/auth", ...rest } = props;
	const [name, setName] = useState("");
	const [email, setEmail] = useState("");
	const [password, setPassword] = useState("");
	const [isHovered, setIsHovered] = useState(false);
	const [googleHover, setGoogleHover] = useState(false);
	const [appleHover, setAppleHover] = useState(false);
	return (
		<div
			style={{
				...rest.style,
				width: "100%",
				display: "flex",
				flexDirection: "row",
				minHeight: "100vh",
				boxSizing: "border-box",
				backgroundColor: colors.white,
			}}
		>
			<style>{`
                .reef-input-inner::placeholder { color: rgb(153, 153, 153); opacity: 1; }
            `}</style>
			<div
				style={{
					flex: 1,
					backgroundColor: colors.surface,
					display: "flex",
					flexDirection: "column",
					justifyContent: "center",
					alignItems: "center",
					padding: "60px 40px",
					borderRight: "2px solid rgb(0, 0, 0)",
					position: "relative",
					overflow: "hidden",
				}}
			>
				<div
					style={{
						position: "absolute",
						top: 0,
						left: 0,
						right: 0,
						bottom: 0,
						opacity: 0.06,
					}}
				>
					{Array.from({
						length: 120,
					}).map((_, i) => (
						<div
							key={i}
							style={{
								position: "absolute",
								width: 4,
								height: 4,
								borderRadius: "50%",
								backgroundColor: colors.black,
								top: `${Math.floor(i / 12) * 9}%`,
								left: `${(i % 12) * 9}%`,
							}}
						/>
					))}
				</div>
				<div
					style={{
						position: "relative",
						zIndex: 1,
						textAlign: "center",
						maxWidth: 400,
					}}
				>
					<h1
						style={{
							fontFamily,
							fontWeight: 900,
							fontSize: 64,
							lineHeight: "1em",
							letterSpacing: "-0.04em",
							textTransform: "uppercase",
							color: colors.black,
							margin: 0,
							marginBottom: 24,
						}}
					>
						{"REEF"}
					</h1>
					<p
						style={{
							fontFamily,
							fontWeight: 500,
							fontSize: 18,
							lineHeight: "1.5em",
							letterSpacing: "-0.04em",
							color: colors.gray600,
							margin: 0,
							marginBottom: 48,
						}}
					>
						{
							"Join thousands of students learning smarter with AI-powered tutoring that adapts to how you think."
						}
					</p>
					{[
						"Free during beta \u2014 all features included",
						"Works with any subject or textbook",
						"No credit card required",
					].map((text, i) => (
						<div
							key={i}
							style={{
								display: "flex",
								alignItems: "center",
								gap: 12,
								marginBottom: 16,
							}}
						>
							<div
								style={{
									width: 28,
									height: 28,
									borderRadius: "8px",
									backgroundColor: colors.primary,
									border: `2px solid ${colors.black}`,
									boxShadow: `3px 3px 0px 0px ${colors.black}`,
									display: "flex",
									alignItems: "center",
									justifyContent: "center",
									flexShrink: 0,
								}}
							>
								<svg
									width={"14"}
									height={"14"}
									viewBox={"0 0 24 24"}
									fill={"none"}
									stroke={"white"}
									strokeWidth={"3"}
									strokeLinecap={"round"}
									strokeLinejoin={"round"}
								>
									<polyline points={"20 6 9 17 4 12"} />
								</svg>
							</div>
							<span
								style={{
									fontFamily,
									fontWeight: 500,
									fontSize: 16,
									lineHeight: "1.5em",
									letterSpacing: "-0.04em",
									color: colors.black,
									textAlign: "left",
								}}
							>
								{text}
							</span>
						</div>
					))}
				</div>
			</div>
			<div
				style={{
					flex: 1,
					display: "flex",
					flexDirection: "column",
					justifyContent: "center",
					alignItems: "center",
					padding: "60px 40px",
					backgroundColor: colors.white,
				}}
			>
				<div
					style={{
						width: 400,
						maxWidth: "100%",
						display: "flex",
						flexDirection: "column",
						boxSizing: "border-box",
					}}
				>
					<h2
						style={{
							fontFamily,
							fontWeight: 900,
							fontSize: 40,
							lineHeight: "1.2em",
							letterSpacing: "-0.04em",
							textTransform: "uppercase",
							color: colors.black,
							margin: 0,
							marginBottom: 8,
							textAlign: "center",
						}}
					>
						{"Get Started"}
					</h2>
					<p
						style={{
							fontFamily,
							fontWeight: 500,
							fontSize: 16,
							lineHeight: "1.5em",
							letterSpacing: "-0.04em",
							color: colors.gray600,
							margin: 0,
							marginBottom: 32,
							textAlign: "center",
						}}
					>
						{"Create your free account"}
					</p>
					<div
						style={{
							display: "flex",
							gap: 12,
							marginBottom: 24,
						}}
					>
						<div
							onMouseEnter={() => setGoogleHover(true)}
							onMouseLeave={() => setGoogleHover(false)}
							style={{
								flex: 1,
								height: 48,
								display: "flex",
								alignItems: "center",
								justifyContent: "center",
								gap: 10,
								backgroundColor: colors.white,
								border: `2px solid ${colors.black}`,
								borderRadius: 12,
								boxShadow: googleHover
									? `2px 2px 0px 0px ${colors.black}`
									: `4px 4px 0px 0px ${colors.black}`,
								transform: googleHover ? "translate(2px, 2px)" : "none",
								cursor: "pointer",
								transition: "box-shadow 0.2s ease, transform 0.2s ease",
							}}
						>
							<GoogleIcon />
							<span
								style={{
									fontFamily,
									fontWeight: 600,
									fontSize: 16,
									letterSpacing: "-0.04em",
									color: colors.black,
								}}
							>
								{"Google"}
							</span>
						</div>
						<div
							onMouseEnter={() => setAppleHover(true)}
							onMouseLeave={() => setAppleHover(false)}
							style={{
								flex: 1,
								height: 48,
								display: "flex",
								alignItems: "center",
								justifyContent: "center",
								gap: 10,
								backgroundColor: colors.white,
								border: `2px solid ${colors.black}`,
								borderRadius: 12,
								boxShadow: appleHover
									? `2px 2px 0px 0px ${colors.black}`
									: `4px 4px 0px 0px ${colors.black}`,
								transform: appleHover ? "translate(2px, 2px)" : "none",
								cursor: "pointer",
								transition: "box-shadow 0.2s ease, transform 0.2s ease",
							}}
						>
							<AppleIcon />
							<span
								style={{
									fontFamily,
									fontWeight: 600,
									fontSize: 16,
									letterSpacing: "-0.04em",
									color: colors.black,
								}}
							>
								{"Apple"}
							</span>
						</div>
					</div>
					<div
						style={{
							display: "flex",
							alignItems: "center",
							gap: 16,
							marginBottom: 24,
						}}
					>
						<div
							style={{
								flex: 1,
								height: 1,
								backgroundColor: colors.gray100,
							}}
						/>
						<span
							style={{
								fontFamily,
								fontWeight: 500,
								fontSize: 14,
								letterSpacing: "-0.04em",
								color: colors.gray600,
								textTransform: "uppercase",
							}}
						>
							{"OR"}
						</span>
						<div
							style={{
								flex: 1,
								height: 1,
								backgroundColor: colors.gray100,
							}}
						/>
					</div>
					<label
						style={{
							fontFamily,
							fontWeight: 600,
							fontSize: 14,
							letterSpacing: "-0.04em",
							color: colors.black,
							marginBottom: 8,
							display: "block",
						}}
					>
						{"Name"}
					</label>
					<div
						style={{
							marginBottom: 16,
						}}
					>
						<InputField
							type={"text"}
							placeholder={"Your full name"}
							value={name}
							onChange={(e) => setName(e.target.value)}
						/>
					</div>
					<label
						style={{
							fontFamily,
							fontWeight: 600,
							fontSize: 14,
							letterSpacing: "-0.04em",
							color: colors.black,
							marginBottom: 8,
							display: "block",
						}}
					>
						{"Email"}
					</label>
					<div
						style={{
							marginBottom: 16,
						}}
					>
						<InputField
							type={"email"}
							placeholder={"Enter your email"}
							value={email}
							onChange={(e) => setEmail(e.target.value)}
						/>
					</div>
					<label
						style={{
							fontFamily,
							fontWeight: 600,
							fontSize: 14,
							letterSpacing: "-0.04em",
							color: colors.black,
							marginBottom: 8,
							display: "block",
						}}
					>
						{"Password"}
					</label>
					<div
						style={{
							marginBottom: 24,
						}}
					>
						<InputField
							type={"password"}
							placeholder={"Create a password"}
							value={password}
							onChange={(e) => setPassword(e.target.value)}
						/>
					</div>
					<div
						role={"button"}
						tabIndex={0}
						onMouseEnter={() => setIsHovered(true)}
						onMouseLeave={() => setIsHovered(false)}
						style={{
							...primaryButton,
							width: "100%",
							boxShadow: isHovered
								? `2px 2px 0px 0px ${colors.black}`
								: `4px 4px 0px 0px ${colors.black}`,
							transform: isHovered ? "translate(2px, 2px)" : "none",
							marginBottom: 24,
						}}
					>
						{"Create Account"}
					</div>
					<p
						style={{
							fontFamily,
							fontWeight: 500,
							fontSize: 14,
							lineHeight: "1.5em",
							letterSpacing: "-0.04em",
							color: colors.gray600,
							textAlign: "center",
							margin: 0,
						}}
					>
						{"Already have an account?"}{" "}
						<a
							href={loginLink}
							style={{
								color: colors.primary,
								textDecoration: "none",
								cursor: "pointer",
								fontWeight: 700,
							}}
						>
							{"Log in"}
						</a>
					</p>
				</div>
			</div>
		</div>
	);
}
addPropertyControls(SignupForm, {
	loginLink: {
		type: ControlType.Link,
		title: "Login Link",
		defaultValue: "/auth",
	},
});

// virtual:signup-form
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale = "", ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<SignupForm {...rest} />
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SignupFormFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={SignupForm}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, SignupForm);
var signup_form_default = ComponentWithRoot;
export { signup_form_default as default };
