// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
// virtual:__routes
var routes = {
  "augiA20Il": {
    path: "/",
    elements: {
      ":jxRb7HA2A": "benefits",
      ":UeW2rucFy": "how-it-work-1",
      ":bmCL3S8v7": "how-it-work-1",
      ":woRj94GG4": "faq",
    },
  },
  "CAx42JOO2": {
    path: "/auth",
  },
};

export {
  routes
};
