// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
// /:https://framerusercontent.com/modules/bYWm5pWKgSawJT22dNFl/jOvSBvnkyzsARDqRGndf/yWUJk0B4D.js
import { fontStore } from "unframer";
fontStore.loadFonts(["FS;Epilogue-medium", "FS;Epilogue-bold", "FS;Epilogue-bold italic", "FS;Epilogue-medium italic"]);
var fonts = [{ explicitInter: true, fonts: [{ cssFamilyName: "Epilogue", source: "fontshare", style: "normal", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/WDPE67UE6MLVKZVLWNP7I6K4BJNXYM75/MEDFVVGRWXNVGRX77CSMLVJYEDA7HC6N/ZCQFQWYK27HETQBG4QFK4TEYPCJZ4KXY.woff2", weight: "500" }, { cssFamilyName: "Epilogue", source: "fontshare", style: "normal", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/Q6PBDKMW3ILHZCUUHJUL7Z5CAEUYIYJT/ACU6JUVISLUN5YPIBAVSNVQX7TIXK7LY/XVEXE7YCBGUS6ROKRHQHPQAR7KODNVQ3.woff2", weight: "700" }, { cssFamilyName: "Epilogue", source: "fontshare", style: "italic", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/ONZH6ZASWZCELVW4GZ5FS2DD4KV34DZY/IWL64III3URHKBZSTXXZCIKPZUGZBYJJ/KVA3QGLTXVRAZQOOPC6T3N7AGN5JIOM5.woff2", weight: "700" }, { cssFamilyName: "Epilogue", source: "fontshare", style: "italic", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/WUXJSSKNWIQSBS5SOEF53KSM42GJBD2L/GLVVTIRT64ZZSWHWACX4KYGJT77NJ2IR/UKD6R7XGPWDZNKQOKYGNPNULQCN345NT.woff2", weight: "500" }] }];
var css = ['.framer-nV9uK .framer-styles-preset-1wx5uu0:not(.rich-text-wrapper), .framer-nV9uK .framer-styles-preset-1wx5uu0.rich-text-wrapper p { --framer-font-family: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 500; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.04em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-8c15ab03-0228-43db-9adb-8c7e76c29ef3, #777777); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }'];
var className = "framer-nV9uK";

export {
  fonts,
  css,
  className
};
