// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
// /:https://framerusercontent.com/modules/iw2GOnzCKd2TRuGxuIrt/TV9NCEmco57WxJActyZA/zB7RjLPJ6.js
import { jsx as _jsx } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, getFontsFromSharedStyle, Link, RichText, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/nhUGkVpQSWBdxCbBR82Y/y0YezeLt0l2dccCrlsL0/ZxQb0MZiY.js
import { fontStore } from "unframer";
fontStore.loadFonts(["FS;Epilogue-semibold", "FS;Epilogue-bold", "FS;Epilogue-bold italic", "FS;Epilogue-medium italic"]);
var fonts = [{ explicitInter: true, fonts: [{ cssFamilyName: "Epilogue", source: "fontshare", style: "normal", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/VET5UWA4MEKQA4WBV5EGM57GLZ6RJ3WC/S45ZC4DS7EIJMXUV6L2BAG5ELV3HN4S3/YDPYKQPH3JEREPOH5AQV4HHIWBADML7M.woff2", weight: "600" }, { cssFamilyName: "Epilogue", source: "fontshare", style: "normal", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/Q6PBDKMW3ILHZCUUHJUL7Z5CAEUYIYJT/ACU6JUVISLUN5YPIBAVSNVQX7TIXK7LY/XVEXE7YCBGUS6ROKRHQHPQAR7KODNVQ3.woff2", weight: "700" }, { cssFamilyName: "Epilogue", source: "fontshare", style: "italic", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/ONZH6ZASWZCELVW4GZ5FS2DD4KV34DZY/IWL64III3URHKBZSTXXZCIKPZUGZBYJJ/KVA3QGLTXVRAZQOOPC6T3N7AGN5JIOM5.woff2", weight: "700" }, { cssFamilyName: "Epilogue", source: "fontshare", style: "italic", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/WUXJSSKNWIQSBS5SOEF53KSM42GJBD2L/GLVVTIRT64ZZSWHWACX4KYGJT77NJ2IR/UKD6R7XGPWDZNKQOKYGNPNULQCN345NT.woff2", weight: "500" }] }];
var css = ['.framer-GVVr7 .framer-styles-preset-1m9leq1:not(.rich-text-wrapper), .framer-GVVr7 .framer-styles-preset-1m9leq1.rich-text-wrapper p { --framer-font-family: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-italic: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 600; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 500; --framer-letter-spacing: -0.04em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-8c15ab03-0228-43db-9adb-8c7e76c29ef3, #777777); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }'];
var className = "framer-GVVr7";

// /:https://framerusercontent.com/modules/iw2GOnzCKd2TRuGxuIrt/TV9NCEmco57WxJActyZA/zB7RjLPJ6.js
var enabledGestures = { COeGqXRVa: { hover: true } };
var serializationHash = "framer-ahKho";
var variantClassNames = { COeGqXRVa: "framer-v-1jbeif5" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants?.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { bounce: 0.2, delay: 0, duration: 0.4, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value ?? config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, label, link, newTab, width, ...props }) => {
  return { ...props, J4dY5fj3I: label ?? props.J4dY5fj3I ?? "Home", LNDVh1koq: link ?? props.LNDVh1koq, UmLY9rSFi: newTab ?? props.UmLY9rSFi };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const fallbackRef = useRef(null);
  const refBinding = ref ?? fallbackRef;
  const defaultLayoutId = React.useId();
  const { activeLocale, setLocale } = useLocaleInfo();
  const componentViewport = useComponentViewport();
  const { style, className: className2, layoutId, variant, LNDVh1koq, UmLY9rSFi, J4dY5fj3I, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ defaultVariant: "COeGqXRVa", enabledGestures, ref: refBinding, variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const sharedStyleClassNames = [className];
  const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId ?? defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsx(Link, { href: LNDVh1koq, motionChild: true, nodeId: "COeGqXRVa", openInNewTab: UmLY9rSFi, scopeId: "zB7RjLPJ6", children: /* @__PURE__ */ _jsx(motion.a, { ...restProps, ...gestureHandlers, className: `${cx(scopingClassNames, "framer-1jbeif5", className2, classNames)} framer-1jnr733`, "data-framer-name": "Default", layoutDependency, layoutId: "COeGqXRVa", ref: refBinding, style: { opacity: 1, ...style }, variants: { "COeGqXRVa-hover": { opacity: 0.5 } }, ...addPropertyOverrides({ "COeGqXRVa-hover": { "data-framer-name": void 0 } }, baseVariant, gestureVariant), children: /* @__PURE__ */ _jsx(RichText, { __fromCanvasComponent: true, children: /* @__PURE__ */ _jsx(React.Fragment, { children: /* @__PURE__ */ _jsx(motion.p, { className: "framer-styles-preset-1m9leq1", "data-styles-preset": "ZxQb0MZiY", style: { "--framer-text-color": "var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))" }, children: "Home" }) }), className: "framer-xny2sl", fonts: ["FS;Epilogue-medium"], layoutDependency, layoutId: "YahFMnhww", style: { "--extracted-r6o4lv": "var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))", "--framer-link-text-color": "rgb(0, 153, 255)", "--framer-link-text-decoration": "underline" }, text: J4dY5fj3I, verticalAlignment: "top", withExternalLayout: true }) }) }) }) }) });
});
var css2 = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-ahKho.framer-1jnr733, .framer-ahKho .framer-1jnr733 { display: block; }", ".framer-ahKho.framer-1jbeif5 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 12px 16px 12px 16px; position: relative; text-decoration: none; width: min-content; }", ".framer-ahKho .framer-xny2sl { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }", ...css];
var FramerzB7RjLPJ6 = withCSS(Component, css2, "framer-ahKho");
var stdin_default = FramerzB7RjLPJ6;
FramerzB7RjLPJ6.displayName = "Navigation Link";
FramerzB7RjLPJ6.defaultProps = { height: 45, width: 70.5 };
addPropertyControls(FramerzB7RjLPJ6, { LNDVh1koq: { title: "Link", type: ControlType.Link }, UmLY9rSFi: { defaultValue: false, title: "New Tab", type: ControlType.Boolean }, J4dY5fj3I: { defaultValue: "Home", displayTextArea: false, title: "Label", type: ControlType.String } });
addFonts(FramerzB7RjLPJ6, [{ explicitInter: true, fonts: [{ cssFamilyName: "Epilogue", source: "fontshare", style: "normal", uiFamilyName: "Epilogue", url: "https://framerusercontent.com/third-party-assets/fontshare/wf/WDPE67UE6MLVKZVLWNP7I6K4BJNXYM75/MEDFVVGRWXNVGRX77CSMLVJYEDA7HC6N/ZCQFQWYK27HETQBG4QFK4TEYPCJZ4KXY.woff2", weight: "500" }] }, ...getFontsFromSharedStyle(fonts)], { supportsExplicitInterCodegen: true });

export {
  stdin_default
};
