// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-F7NMXMNT.js";
import "./chunks/chunk-I5UJFPX7.js";
import "./chunks/chunk-H3CR5NCT.js";
import { routes } from "./chunks/chunk-VG7AXKTA.js";

// virtual:accordion
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/jrxX9zQqVGNjgO0dh1UE/xw6WRASlWY4n5x3ZzhxR/drljal8QL.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	ComponentViewportProvider,
	cx,
	forwardLoader,
	getFonts,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var QuestionFonts = getFonts(stdin_default);
var serializationHash = "framer-3OB4o";
var variantClassNames = {
	kcBgZw0P9: "framer-v-i8ltlx",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "kcBgZw0P9",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-i8ltlx",
							className,
							classNames,
						)}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"kcBgZw0P9"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 + 0 + 0)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1tbdpos-container"}
								layoutDependency={layoutDependency}
								layoutId={"HQoW3dFdf-container"}
								nodeId={"HQoW3dFdf"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "HQoW3dFdf",
									layoutId: "HQoW3dFdf",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt:
										"ChatGPT waits for you to type a question. Reef watches you work in real time\u2014it reads your handwriting, understands the problem you're solving, and speaks up when you're stuck. No copy-pasting, no context-switching. It's a tutor that can read the room.",
									zcvQcwmWp: "HOW IS THIS DIFFERENT FROM CHATGPT/notability?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 +
									80 +
									20)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-15dlw73-container"}
								layoutDependency={layoutDependency}
								layoutId={"rz4S5O2Aq-container"}
								nodeId={"rz4S5O2Aq"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "rz4S5O2Aq",
									layoutId: "rz4S5O2Aq",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt:
										"Your notes and documents stay on your device and in your private iCloud. We never use your work to train AI models.",
									zcvQcwmWp: "IS MY DATA PRIVATE?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 +
									160 +
									40)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-cgi204-container"}
								layoutDependency={layoutDependency}
								layoutId={"qS58uPFpf-container"}
								nodeId={"qS58uPFpf"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "qS58uPFpf",
									layoutId: "qS58uPFpf",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt:
										"Reef doesn't give you answers\u2014it helps you find them. Think of it like office hours that never close. It watches your work, spots mistakes, and nudges you in the right direction.",
									zcvQcwmWp: "IS THIS CHEATING?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 +
									240 +
									60)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-pqqz5k-container"}
								layoutDependency={layoutDependency}
								layoutId={"gNsCFgXPK-container"}
								nodeId={"gNsCFgXPK"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "gNsCFgXPK",
									layoutId: "gNsCFgXPK",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt:
										"Math, physics, chemistry, biology, engineering, and more. If it's a STEM course with problem sets, Reef can help. We're expanding to other subjects soon.",
									zcvQcwmWp: "WHAT SUBJECTS DOES REEF SUPPORT?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 +
									320 +
									80)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-18gfm7z-container"}
								layoutDependency={layoutDependency}
								layoutId={"ddulI4TqN-container"}
								nodeId={"ddulI4TqN"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "ddulI4TqN",
									layoutId: "ddulI4TqN",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt:
										"You don't need one, but Reef is built around handwriting. An Apple Pencil unlocks the full experience\u2014pressure sensitivity, palm rejection, and real-time recognition as you write.",
									zcvQcwmWp: "DO I NEED AN APPLE PENCIL?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 +
									400 +
									100)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1piq97k-container"}
								layoutDependency={layoutDependency}
								layoutId={"aFuap2dNy-container"}
								nodeId={"aFuap2dNy"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "aFuap2dNy",
									layoutId: "aFuap2dNy",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt: "No. It's seen worse. Much worse.",
									zcvQcwmWp: "WILL THE AI JUDGE ME FOR MY HANDWRITING?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 +
									480 +
									120)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-b6r14x-container"}
								layoutDependency={layoutDependency}
								layoutId={"gLnpB93u6-container"}
								nodeId={"gLnpB93u6"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "gLnpB93u6",
									layoutId: "gLnpB93u6",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt:
										"Your notes sync to iCloud. Your dog would need your Apple ID.",
									zcvQcwmWp: "CAN MY DOG STILL EAT MY HOMEWORK?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<ComponentViewportProvider
							height={80}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 779.467) - 0 - 780) / 2 +
									560 +
									140)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1561d59-container"}
								layoutDependency={layoutDependency}
								layoutId={"x2pwpEwtu-container"}
								nodeId={"x2pwpEwtu"}
								rendersWithMotion={true}
								scopeId={"drljal8QL"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "x2pwpEwtu",
									layoutId: "x2pwpEwtu",
									style: {
										width: "100%",
									},
									variant: matchVariant("uvksLtanA"),
									width: "100%",
									WPHRcrcmt:
										"You read this entire FAQ instead of studying. Yes. Immediately.",
									zcvQcwmWp: "OKAY BUT SERIOUSLY, SHOULD I DOWNLOAD THIS?",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-3OB4o.framer-5uj7y4, .framer-3OB4o .framer-5uj7y4 { display: block; }",
	".framer-3OB4o.framer-i8ltlx { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 600px; }",
	".framer-3OB4o .framer-1tbdpos-container, .framer-3OB4o .framer-15dlw73-container, .framer-3OB4o .framer-cgi204-container, .framer-3OB4o .framer-pqqz5k-container, .framer-3OB4o .framer-18gfm7z-container, .framer-3OB4o .framer-1piq97k-container, .framer-3OB4o .framer-b6r14x-container, .framer-3OB4o .framer-1561d59-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var Framerdrljal8QL = withCSS(Component, css, "framer-3OB4o");
var stdin_default2 = Framerdrljal8QL;
Framerdrljal8QL.displayName = "Accordion";
Framerdrljal8QL.defaultProps = {
	height: 779.467,
	width: 600,
};
addFonts(
	Framerdrljal8QL,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...QuestionFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
Framerdrljal8QL.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:accordion
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AccordionFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var accordion_default = ComponentWithRoot;
export { accordion_default as default };
