// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * oncI8DW7UY1Change?: undefined // oncI8DW7UY1Change
 * description?: string // Description
 * onslWmtt_VCCHange?: undefined // onslWmtt_VCCHange
 * price?: string // Price
 * onzNizceH4fChange?: undefined // onzNizceH4fChange
 * background?: string // Background
 * buttonLink?: string // Button - Link
 * buttonNewTab?: boolean // Button - NewTab
 * onQraNpMhseChange?: undefined // onQraNpMhseChange
 * buttonLabel?: string // Button - Label
 * onjQxAXHNZPCHange?: undefined // onjQxAXHNZPCHange
 * feature1?: string // Feature 1
 * onWQAYcKcERCHange?: undefined // onWQAYcKcERCHange
 * feature2?: string // Feature 2
 * ono8Y0km2fpChange?: undefined // ono8Y0km2fpChange
 * feature3?: string // Feature 3
 * onrOjUNQGSCHange?: undefined // onrOjUNQGSCHange
 * feature4?: string // Feature 4
 * ongmb6nOqbxChange?: undefined // ongmb6nOqbxChange
 * feature5?: string // Feature 5
 * onbkFMOQKI4Change?: undefined // onbkFMOQKI4Change
 * fill?: string // Fill
}} Props

 */
import {
	className as className3,
	css as css3,
	fonts as fonts3,
} from "./chunks/chunk-I5UJFPX7.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-YKD4AROT.js";
import { stdin_default } from "./chunks/chunk-DNUIZVT6.js";
import "./chunks/chunk-MMET2FZU.js";
import { className, css, fonts } from "./chunks/chunk-H3CR5NCT.js";
import { routes } from "./chunks/chunk-VG7AXKTA.js";

// virtual:pricing-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fjTNrztvI4MXXcfP6jwQ/0DcbGRquFbpzTgsoSJem/SCKV2zL6D.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/kInDmZIDcV8yRFkL40Tq/C3K101eRhyWvr8uJDZdB/iJ0GIKQvm.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"FS;Epilogue-black",
	"FS;Epilogue-black",
	"FS;Epilogue-black italic",
	"FS;Epilogue-black italic",
]);
var fonts4 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Epilogue",
				source: "fontshare",
				style: "normal",
				uiFamilyName: "Epilogue",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/HW7DA5MZIQCIMCOUSVAFDKYIAGBQ2EPW/64YUI6PFX4KLJZLCCPVY7Z5FARAYQ3DX/NJMCUXH2I67M6ZVSE6EO6LRTO3M22XCT.woff2",
				weight: "900",
			},
			{
				cssFamilyName: "Epilogue",
				source: "fontshare",
				style: "italic",
				uiFamilyName: "Epilogue",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/KK544MJIFZ3MDT67AKIUKOFLISMBMXOA/D7CFVQTPQ3OCLOZ7ZC772LEWAQV7R7EN/KZRBQZD7DG3TFKTGCJMNODPANWHK6W6G.woff2",
				weight: "900",
			},
		],
	},
];
var css4 = [
	'.framer-armj4 .framer-styles-preset-1414slq:not(.rich-text-wrapper), .framer-armj4 .framer-styles-preset-1414slq.rich-text-wrapper h2 { --framer-font-family: "Epilogue", sans-serif; --framer-font-family-bold: "Epilogue", sans-serif; --framer-font-family-bold-italic: "Epilogue", sans-serif; --framer-font-family-italic: "Epilogue", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 40px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 900; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 900; --framer-letter-spacing: -0.04em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; }',
	'@media (max-width: 1199px) and (min-width: 810px) { .framer-armj4 .framer-styles-preset-1414slq:not(.rich-text-wrapper), .framer-armj4 .framer-styles-preset-1414slq.rich-text-wrapper h2 { --framer-font-family: "Epilogue", sans-serif; --framer-font-family-bold: "Epilogue", sans-serif; --framer-font-family-bold-italic: "Epilogue", sans-serif; --framer-font-family-italic: "Epilogue", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 32px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 900; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 900; --framer-letter-spacing: -0.04em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }',
	'@media (max-width: 809px) and (min-width: 0px) { .framer-armj4 .framer-styles-preset-1414slq:not(.rich-text-wrapper), .framer-armj4 .framer-styles-preset-1414slq.rich-text-wrapper h2 { --framer-font-family: "Epilogue", sans-serif; --framer-font-family-bold: "Epilogue", sans-serif; --framer-font-family-bold-italic: "Epilogue", sans-serif; --framer-font-family-italic: "Epilogue", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 26px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 900; --framer-font-weight-bold: 900; --framer-font-weight-bold-italic: 900; --framer-font-weight-italic: 900; --framer-letter-spacing: -0.04em; --framer-line-height: 1.2em; --framer-paragraph-spacing: 40px; --framer-text-alignment: center; --framer-text-color: var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, #000000); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: uppercase; } }',
];
var className4 = "framer-armj4";

// /:https://framerusercontent.com/modules/ewuIXTOgCVmTY7FMCeLC/4Dv0SiRi64hH2uQYtN3b/JGN4yq03n.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([
	"FS;Epilogue-bold",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts5 = [
	{
		explicitInter: true,
		fonts: [
			{
				cssFamilyName: "Epilogue",
				source: "fontshare",
				style: "normal",
				uiFamilyName: "Epilogue",
				url: "https://framerusercontent.com/third-party-assets/fontshare/wf/Q6PBDKMW3ILHZCUUHJUL7Z5CAEUYIYJT/ACU6JUVISLUN5YPIBAVSNVQX7TIXK7LY/XVEXE7YCBGUS6ROKRHQHPQAR7KODNVQ3.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/DpPBYI0sL4fYLgAkX8KXOPVt7c.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/4RAEQdEOrcnDkhHiiCbJOw92Lk.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/1K3W8DizY3v4emK8Mb08YHxTbs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/tUSCtfYVM1I1IchuyCwz9gDdQ.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/VgYFWiwsAC5OYxAycRXXvhze58.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/syRNPWzAMIrcJ3wIlPIP43KjQs.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "normal",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/GIryZETIX4IFypco5pYZONKhJIo.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/H89BbHkbHDzlxZzxi8uPzTsp90.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/u6gJwDuwB143kpNK1T1MDKDWkMc.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/43sJ6MfOPh1LCJt46OvyDuSbA6o.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/wccHG0r4gBDAIRhfHiOlq6oEkqw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/WZ367JPwf9bRW6LdTHN8rXgSjw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/ia3uin3hQWqDrVloC1zEtYHWw.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/2A4Xx7CngadFGlVV4xrO06OBHY.woff2",
				weight: "700",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
				url: "https://framerusercontent.com/assets/CfMzU8w2e7tHgF4T4rATMPuWosA.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
				url: "https://framerusercontent.com/assets/867QObYax8ANsfX4TGEVU9YiCM.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+1F00-1FFF",
				url: "https://framerusercontent.com/assets/Oyn2ZbENFdnW7mt2Lzjk1h9Zb9k.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange: "U+0370-03FF",
				url: "https://framerusercontent.com/assets/cdAe8hgZ1cMyLu9g005pAW3xMo.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
				url: "https://framerusercontent.com/assets/DOfvtmE1UplCq161m6Hj8CSQYg.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
				url: "https://framerusercontent.com/assets/pKRFNWFoZl77qYCAIp84lN1h944.woff2",
				weight: "400",
			},
			{
				cssFamilyName: "Inter",
				source: "framer",
				style: "italic",
				uiFamilyName: "Inter",
				unicodeRange:
					"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
				url: "https://framerusercontent.com/assets/tKtBcDnBMevsEEJKdNGhhkLzYo.woff2",
				weight: "400",
			},
		],
	},
];
var css5 = [
	'.framer-NRshx .framer-styles-preset-6joauu:not(.rich-text-wrapper), .framer-NRshx .framer-styles-preset-6joauu.rich-text-wrapper p { --framer-font-family: "Epilogue", "Epilogue Placeholder", sans-serif; --framer-font-family-bold: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter", "Inter Placeholder", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-variation-axes: normal; --framer-font-weight: 700; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: -0.04em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 20px; --framer-text-alignment: center; --framer-text-color: var(--token-8c15ab03-0228-43db-9adb-8c7e76c29ef3, #777777); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className5 = "framer-NRshx";

// /:https://framerusercontent.com/modules/fjTNrztvI4MXXcfP6jwQ/0DcbGRquFbpzTgsoSJem/SCKV2zL6D.js
var ButtonFonts = getFonts(stdin_default);
var serializationHash = "framer-r7cQV";
var variantClassNames = {
	Pp3AXOVe3: "framer-v-1vxx77",
};
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var useStateVariable = (externalState, setExternalState) => {
	const [internalState, setInternalState] = React.useState(externalState);
	const [previousExternalState, setPreviousExternalState] =
		React.useState(externalState);
	if (setExternalState) {
		return [externalState, setExternalState];
	}
	if (externalState !== previousExternalState) {
		setInternalState(externalState);
		setPreviousExternalState(externalState);
	}
	return [internalState, setInternalState];
};
var getProps = ({
	background,
	buttonLabel,
	buttonLink,
	buttonNewTab,
	description,
	feature1,
	feature2,
	feature3,
	feature4,
	feature5,
	fill,
	height,
	id,
	price,
	title,
	width,
	...props
}) => {
	return {
		...props,
		bkFMOQkI4: feature5 ?? props.bkFMOQkI4 ?? "Custom domain",
		cI8DW7UY1: title ?? props.cI8DW7UY1 ?? "Starter",
		dP_dMC_Fk:
			background ??
			props.dP_dMC_Fk ??
			"var(--token-fdcc5b21-a997-46c1-a990-9f9c0159a383, rgb(248, 214, 179))",
		gmb6nOqbx: feature4 ?? props.gmb6nOqbx ?? "Email support",
		jQxAXhNZP: buttonLabel ?? props.jQxAXhNZP ?? "Start for free",
		o8Y0km2fp: feature2 ?? props.o8Y0km2fp ?? "Up to 100 students",
		oRjjMprtS: buttonLink ?? props.oRjjMprtS,
		QraNpMhse: buttonNewTab ?? props.QraNpMhse,
		rOjUN_qGS: feature3 ?? props.rOjUN_qGS ?? "Basic analytics",
		slWmtt_VC:
			description ??
			props.slWmtt_VC ??
			"For creators who want to launch their first course and keep things simple",
		WQAycKcER: feature1 ?? props.WQAycKcER ?? "1 course",
		XMg8onXK1:
			fill ??
			props.XMg8onXK1 ??
			"var(--token-10bc40bb-604b-41d4-b321-4b409afa6a9f, rgb(255, 219, 88))",
		zNizceH4f: price ?? props.zNizceH4f ?? "19.99 \u20AC",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className6,
		layoutId,
		variant,
		cI8DW7UY1: cI8DW7UY12,
		slWmtt_VC: slWmtt_VC2,
		zNizceH4f: zNizceH4f2,
		dP_dMC_Fk: dP_dMC_Fk2,
		oRjjMprtS: oRjjMprtS2,
		QraNpMhse: externalQraNpMhse,
		onQraNpMhseChange: setExternalQraNpMhse,
		jQxAXhNZP: externaljQxAXhNZP,
		onjQxAXhNZPChange: setExternaljQxAXhNZP,
		WQAycKcER: WQAycKcER2,
		o8Y0km2fp: o8Y0km2fp2,
		rOjUN_qGS: rOjUN_qGS2,
		gmb6nOqbx: gmb6nOqbx2,
		bkFMOQkI4: bkFMOQkI42,
		XMg8onXK1: XMg8onXK12,
		...restProps
	} = getProps(props);
	const [QraNpMhse2, setQraNpMhse2] = useStateVariable(
		externalQraNpMhse,
		setExternalQraNpMhse,
	);
	const [jQxAXhNZP2, setjQxAXhNZP2] = useStateVariable(
		externaljQxAXhNZP,
		setExternaljQxAXhNZP,
	);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "Pp3AXOVe3",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [
		className2,
		className,
		className4,
		className3,
		className5,
	];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1vxx77",
							className6,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"Pp3AXOVe3"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "2px",
							"--border-color":
								"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
							"--border-left-width": "2px",
							"--border-right-width": "2px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							backgroundColor: dP_dMC_Fk2,
							boxShadow:
								"8px 8px 0px 0px var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
							...style,
						}}
					>
						<motion.div
							className={"framer-xcipnf"}
							data-framer-name={"wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"fSlP6H8pe"}
						>
							<motion.div
								className={"framer-1qntzue"}
								data-framer-name={"wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"EKnLJWYVl"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-s5qiw5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"CH_AjkywX"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={cI8DW7UY12}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-1w6sc1n"}
											data-styles-preset={"WCABqTCb2"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"Starter"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-g3v6xf"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"svhd4f0wu"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={slWmtt_VC2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1wx5uu0"}
											data-styles-preset={"yWUJk0B4D"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
											}}
										>
											{
												"For creators who want to launch their first course and keep things simple"
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-18qococ"}
								data-framer-name={"wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"eXqoENF7X"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1qdk9h1"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"gReM3Y8Ww"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={zNizceH4f2}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1414slq"}
											data-styles-preset={"iJ0GIKQvm"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"19.99 \u20AC"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-39p4xl"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"hhPM17EBm"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-18inr98"}
											data-styles-preset={"paYT5vbnW"}
										>
											{"/ mo"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1e8u1uy"}
								data-framer-name={"wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"S4uEikDFw"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1l4l5yy"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"rBhfclAiN"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-6joauu"}
											data-styles-preset={"JGN4yq03n"}
											style={{
												"--framer-text-alignment": "justify",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
											}}
										>
											{"INCLUDES:"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<motion.div
									className={"framer-1t5cnst"}
									data-framer-name={"wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"n1rQq5F6C"}
								>
									<SVG
										className={"framer-rqvc5y"}
										data-framer-name={"Graphic"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"NfzYXwA50"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16"><path d="M 15.985 8 L 15.875 7.978 C 14.09 7.624 11.867 7.414 9.567 7.351 C 11.182 5.641 12.63 3.886 13.644 2.352 C 12.111 3.366 10.356 4.815 8.645 6.43 C 8.579 4.077 8.361 1.814 7.996 0.011 C 7.631 1.814 7.414 4.077 7.347 6.43 C 5.637 4.815 3.882 3.366 2.348 2.352 C 3.362 3.886 4.811 5.641 6.426 7.351 C 4.074 7.418 1.81 7.635 0.007 8 C 1.81 8.365 4.074 8.583 6.426 8.649 C 4.844 10.323 3.421 12.041 2.411 13.552 L 2.348 13.648 L 2.444 13.585 C 3.956 12.571 5.674 11.148 7.347 9.571 C 7.414 11.871 7.62 14.09 7.974 15.878 L 7.996 15.989 L 8.018 15.878 C 8.372 14.094 8.582 11.871 8.645 9.571 C 10.319 11.152 12.037 12.575 13.548 13.585 L 13.644 13.648 L 13.582 13.552 C 12.568 12.041 11.145 10.323 9.567 8.649 C 11.867 8.583 14.087 8.376 15.875 8.022 Z" fill="var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))"></path></svg>'
										}
										svgContentId={9284598072}
										withExternalLayout={true}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1baa0oc"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"LnmtvJvKo"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={WQAycKcER2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1wx5uu0"}
												data-styles-preset={"yWUJk0B4D"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
												}}
											>
												{"1 course"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-uq7y18"}
									data-framer-name={"wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"KpcPHuvxt"}
								>
									<SVG
										className={"framer-1k1byiu"}
										data-framer-name={"Graphic"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"pyKmSEY1r"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16"><path d="M 15.985 8 L 15.875 7.978 C 14.09 7.624 11.867 7.414 9.567 7.351 C 11.182 5.641 12.63 3.886 13.644 2.352 C 12.111 3.366 10.356 4.815 8.645 6.43 C 8.579 4.077 8.361 1.814 7.996 0.011 C 7.631 1.814 7.414 4.077 7.347 6.43 C 5.637 4.815 3.882 3.366 2.348 2.352 C 3.362 3.886 4.811 5.641 6.426 7.351 C 4.074 7.418 1.81 7.635 0.007 8 C 1.81 8.365 4.074 8.583 6.426 8.649 C 4.844 10.323 3.421 12.041 2.411 13.552 L 2.348 13.648 L 2.444 13.585 C 3.956 12.571 5.674 11.148 7.347 9.571 C 7.414 11.871 7.62 14.09 7.974 15.878 L 7.996 15.989 L 8.018 15.878 C 8.372 14.094 8.582 11.871 8.645 9.571 C 10.319 11.152 12.037 12.575 13.548 13.585 L 13.644 13.648 L 13.582 13.552 C 12.568 12.041 11.145 10.323 9.567 8.649 C 11.867 8.583 14.087 8.376 15.875 8.022 Z" fill="var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))"></path></svg>'
										}
										svgContentId={9284598072}
										withExternalLayout={true}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-thvocn"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"S9tUtNUzz"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={o8Y0km2fp2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1wx5uu0"}
												data-styles-preset={"yWUJk0B4D"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
												}}
											>
												{"Up to 100 students"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-ut8iy4"}
									data-framer-name={"wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"W11X7y0iM"}
								>
									<SVG
										className={"framer-rf8lfh"}
										data-framer-name={"Graphic"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"fAqWDsn0m"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16"><path d="M 15.985 8 L 15.875 7.978 C 14.09 7.624 11.867 7.414 9.567 7.351 C 11.182 5.641 12.63 3.886 13.644 2.352 C 12.111 3.366 10.356 4.815 8.645 6.43 C 8.579 4.077 8.361 1.814 7.996 0.011 C 7.631 1.814 7.414 4.077 7.347 6.43 C 5.637 4.815 3.882 3.366 2.348 2.352 C 3.362 3.886 4.811 5.641 6.426 7.351 C 4.074 7.418 1.81 7.635 0.007 8 C 1.81 8.365 4.074 8.583 6.426 8.649 C 4.844 10.323 3.421 12.041 2.411 13.552 L 2.348 13.648 L 2.444 13.585 C 3.956 12.571 5.674 11.148 7.347 9.571 C 7.414 11.871 7.62 14.09 7.974 15.878 L 7.996 15.989 L 8.018 15.878 C 8.372 14.094 8.582 11.871 8.645 9.571 C 10.319 11.152 12.037 12.575 13.548 13.585 L 13.644 13.648 L 13.582 13.552 C 12.568 12.041 11.145 10.323 9.567 8.649 C 11.867 8.583 14.087 8.376 15.875 8.022 Z" fill="var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))"></path></svg>'
										}
										svgContentId={9284598072}
										withExternalLayout={true}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-y9jau5"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"r6k_C4_hg"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={rOjUN_qGS2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1wx5uu0"}
												data-styles-preset={"yWUJk0B4D"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
												}}
											>
												{"Basic analytics"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-toos24"}
									data-framer-name={"wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"uSzg2aQyK"}
								>
									<SVG
										className={"framer-tgmzhk"}
										data-framer-name={"Graphic"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"MYCim_p6x"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16"><path d="M 15.985 8 L 15.875 7.978 C 14.09 7.624 11.867 7.414 9.567 7.351 C 11.182 5.641 12.63 3.886 13.644 2.352 C 12.111 3.366 10.356 4.815 8.645 6.43 C 8.579 4.077 8.361 1.814 7.996 0.011 C 7.631 1.814 7.414 4.077 7.347 6.43 C 5.637 4.815 3.882 3.366 2.348 2.352 C 3.362 3.886 4.811 5.641 6.426 7.351 C 4.074 7.418 1.81 7.635 0.007 8 C 1.81 8.365 4.074 8.583 6.426 8.649 C 4.844 10.323 3.421 12.041 2.411 13.552 L 2.348 13.648 L 2.444 13.585 C 3.956 12.571 5.674 11.148 7.347 9.571 C 7.414 11.871 7.62 14.09 7.974 15.878 L 7.996 15.989 L 8.018 15.878 C 8.372 14.094 8.582 11.871 8.645 9.571 C 10.319 11.152 12.037 12.575 13.548 13.585 L 13.644 13.648 L 13.582 13.552 C 12.568 12.041 11.145 10.323 9.567 8.649 C 11.867 8.583 14.087 8.376 15.875 8.022 Z" fill="var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))"></path></svg>'
										}
										svgContentId={9284598072}
										withExternalLayout={true}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-9ddxg3"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"dPvFnO_51"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={gmb6nOqbx2}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1wx5uu0"}
												data-styles-preset={"yWUJk0B4D"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
												}}
											>
												{"Email support"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-4ph4n9"}
									data-framer-name={"wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"GZ5HaVAif"}
								>
									<SVG
										className={"framer-13bkxs7"}
										data-framer-name={"Graphic"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"UHYyKO2lO"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 16 16"><path d="M 15.985 8 L 15.875 7.978 C 14.09 7.624 11.867 7.414 9.567 7.351 C 11.182 5.641 12.63 3.886 13.644 2.352 C 12.111 3.366 10.356 4.815 8.645 6.43 C 8.579 4.077 8.361 1.814 7.996 0.011 C 7.631 1.814 7.414 4.077 7.347 6.43 C 5.637 4.815 3.882 3.366 2.348 2.352 C 3.362 3.886 4.811 5.641 6.426 7.351 C 4.074 7.418 1.81 7.635 0.007 8 C 1.81 8.365 4.074 8.583 6.426 8.649 C 4.844 10.323 3.421 12.041 2.411 13.552 L 2.348 13.648 L 2.444 13.585 C 3.956 12.571 5.674 11.148 7.347 9.571 C 7.414 11.871 7.62 14.09 7.974 15.878 L 7.996 15.989 L 8.018 15.878 C 8.372 14.094 8.582 11.871 8.645 9.571 C 10.319 11.152 12.037 12.575 13.548 13.585 L 13.644 13.648 L 13.582 13.552 C 12.568 12.041 11.145 10.323 9.567 8.649 C 11.867 8.583 14.087 8.376 15.875 8.022 Z" fill="var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))"></path></svg>'
										}
										svgContentId={9284598072}
										withExternalLayout={true}
									/>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-1t6ybv4"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"Pq2teWqXn"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										text={bkFMOQkI42}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-1wx5uu0"}
												data-styles-preset={"yWUJk0B4D"}
												style={{
													"--framer-text-alignment": "left",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
												}}
											>
												{"Custom domain"}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
							</motion.div>
							<ComponentViewportProvider
								height={48}
								width={`calc(max(${componentViewport?.width || "100vw"}, 1px) - 40px)`}
								y={
									(componentViewport?.y || 0) +
									0 +
									20 +
									((((componentViewport?.height || 600) - 0) * 1 -
										40 -
										1122.6) /
										2 +
										954.6 +
										120)
								}
							>
								<SmartComponentScopedContainer
									className={"framer-1fia7wc-container"}
									layoutDependency={layoutDependency}
									layoutId={"As6O5Mnqk-container"}
									nodeId={"As6O5Mnqk"}
									rendersWithMotion={true}
									scopeId={"SCKV2zL6D"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "As6O5Mnqk",
										layoutId: "As6O5Mnqk",
										onUyxF8MkP4Change: setQraNpMhse2,
										onXy29tPt0iChange: setjQxAXhNZP2,
										style: {
											width: "100%",
										},
										UyxF8MkP4: QraNpMhse2,
										variant: matchVariant("iFwbrC864"),
										width: "100%",
										Xy29tPt0i: jQxAXhNZP2,
										Y3kwMmSe8: XMg8onXK12,
										ylibWg5Df: oRjjMprtS2,
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css6 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-r7cQV.framer-1w3w0dp, .framer-r7cQV .framer-1w3w0dp { display: block; }",
	".framer-r7cQV.framer-1vxx77 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: 600px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 350px; }",
	".framer-r7cQV .framer-xcipnf { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 40px; height: 100%; justify-content: center; overflow: visible; padding: 20px; position: relative; width: 1px; }",
	".framer-r7cQV .framer-1qntzue { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-r7cQV .framer-s5qiw5, .framer-r7cQV .framer-1l4l5yy { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-r7cQV .framer-g3v6xf { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-r7cQV .framer-18qococ { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-r7cQV .framer-1qdk9h1, .framer-r7cQV .framer-39p4xl { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-r7cQV .framer-1e8u1uy { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-r7cQV .framer-1t5cnst, .framer-r7cQV .framer-uq7y18, .framer-r7cQV .framer-ut8iy4, .framer-r7cQV .framer-toos24, .framer-r7cQV .framer-4ph4n9 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-r7cQV .framer-rqvc5y, .framer-r7cQV .framer-1k1byiu, .framer-r7cQV .framer-rf8lfh, .framer-r7cQV .framer-tgmzhk, .framer-r7cQV .framer-13bkxs7 { flex: none; height: 16px; position: relative; width: 16px; }",
	".framer-r7cQV .framer-1baa0oc, .framer-r7cQV .framer-thvocn, .framer-r7cQV .framer-y9jau5, .framer-r7cQV .framer-9ddxg3, .framer-r7cQV .framer-1t6ybv4 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-r7cQV .framer-1fia7wc-container { flex: none; height: auto; position: relative; width: 100%; }",
	...css2,
	...css,
	...css4,
	...css3,
	...css5,
	'.framer-r7cQV[data-border="true"]::after, .framer-r7cQV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerSCKV2zL6D = withCSS(Component, css6, "framer-r7cQV");
var stdin_default2 = FramerSCKV2zL6D;
FramerSCKV2zL6D.displayName = "Pricing Card";
FramerSCKV2zL6D.defaultProps = {
	height: 600,
	width: 350,
};
addPropertyControls(FramerSCKV2zL6D, {
	cI8DW7UY1: {
		defaultValue: "Starter",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	oncI8DW7UY1Change: {
		changes: "cI8DW7UY1",
		type: ControlType.ChangeHandler,
	},
	slWmtt_VC: {
		defaultValue:
			"For creators who want to launch their first course and keep things simple",
		displayTextArea: false,
		title: "Description",
		type: ControlType.String,
	},
	onslWmtt_VCChange: {
		changes: "slWmtt_VC",
		type: ControlType.ChangeHandler,
	},
	zNizceH4f: {
		defaultValue: "19.99 \u20AC",
		displayTextArea: false,
		title: "Price",
		type: ControlType.String,
	},
	onzNizceH4fChange: {
		changes: "zNizceH4f",
		type: ControlType.ChangeHandler,
	},
	dP_dMC_Fk: {
		defaultValue:
			'var(--token-fdcc5b21-a997-46c1-a990-9f9c0159a383, rgb(248, 214, 179)) /* {"name":"orange"} */',
		title: "Background",
		type: ControlType.Color,
	},
	oRjjMprtS: {
		title: "Button - Link",
		type: ControlType.Link,
	},
	QraNpMhse: {
		defaultValue: false,
		title: "Button - NewTab",
		type: ControlType.Boolean,
	},
	onQraNpMhseChange: {
		changes: "QraNpMhse",
		type: ControlType.ChangeHandler,
	},
	jQxAXhNZP: {
		defaultValue: "Start for free",
		displayTextArea: false,
		title: "Button - Label",
		type: ControlType.String,
	},
	onjQxAXhNZPChange: {
		changes: "jQxAXhNZP",
		type: ControlType.ChangeHandler,
	},
	WQAycKcER: {
		defaultValue: "1 course",
		displayTextArea: false,
		title: "Feature 1",
		type: ControlType.String,
	},
	onWQAycKcERChange: {
		changes: "WQAycKcER",
		type: ControlType.ChangeHandler,
	},
	o8Y0km2fp: {
		defaultValue: "Up to 100 students",
		displayTextArea: false,
		title: "Feature 2",
		type: ControlType.String,
	},
	ono8Y0km2fpChange: {
		changes: "o8Y0km2fp",
		type: ControlType.ChangeHandler,
	},
	rOjUN_qGS: {
		defaultValue: "Basic analytics",
		displayTextArea: false,
		title: "Feature 3",
		type: ControlType.String,
	},
	onrOjUN_qGSChange: {
		changes: "rOjUN_qGS",
		type: ControlType.ChangeHandler,
	},
	gmb6nOqbx: {
		defaultValue: "Email support",
		displayTextArea: false,
		title: "Feature 4",
		type: ControlType.String,
	},
	ongmb6nOqbxChange: {
		changes: "gmb6nOqbx",
		type: ControlType.ChangeHandler,
	},
	bkFMOQkI4: {
		defaultValue: "Custom domain",
		displayTextArea: false,
		title: "Feature 5",
		type: ControlType.String,
	},
	onbkFMOQkI4Change: {
		changes: "bkFMOQkI4",
		type: ControlType.ChangeHandler,
	},
	XMg8onXK1: {
		defaultValue:
			"var(--token-10bc40bb-604b-41d4-b321-4b409afa6a9f, rgb(255, 219, 88))",
		title: "Fill",
		type: ControlType.Color,
	},
});
addFonts(
	FramerSCKV2zL6D,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...ButtonFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts4),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts5),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerSCKV2zL6D.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(stdin_default, {}, context)]);
	},
};

// virtual:pricing-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PricingCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var pricing_card_default = ComponentWithRoot;
export { pricing_card_default as default };
