// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Single' | 'Double' | 'Double - Mobile' | 'problem-card' // Variant
 * headline?: string // Headline
 * subline?: string // Subline
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * background?: string // Background
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-YKD4AROT";
import { className, css, fonts } from "./chunks/chunk-H3CR5NCT";
import { routes } from "./chunks/chunk-VG7AXKTA";

// virtual:features-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/iBDWDtH7rIpjudK2vwYf/kyokBYobMHgAuxygGRtj/Zp4iwkAsa.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["ez7OSsTNr", "WXVIZlnuV", "Qfwu_ux6i", "S8hi1XwTG"];
var serializationHash = "framer-CAKEG";
var variantClassNames = {
	ez7OSsTNr: "framer-v-1f6l56w",
	Qfwu_ux6i: "framer-v-mc29v3",
	S8hi1XwTG: "framer-v-1h7jz2a",
	WXVIZlnuV: "framer-v-1uq5497",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Double - Mobile": "Qfwu_ux6i",
	"problem-card": "S8hi1XwTG",
	Double: "WXVIZlnuV",
	Single: "ez7OSsTNr",
};
var Variants = motion.create(React.Fragment);
var getProps = ({
	background,
	headline,
	height,
	id,
	image,
	subline,
	width,
	...props
}) => {
	return {
		...props,
		AI2SJBoqv: headline ?? props.AI2SJBoqv ?? "Too many tools to handle",
		feFxhFHQx:
			background ??
			props.feFxhFHQx ??
			"var(--token-735d697b-5a03-49fe-9b66-80e6a14713f9, rgb(255, 255, 255))",
		j6FrGQEgK: image ?? props.j6FrGQEgK,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "ez7OSsTNr",
		X08wkFYiN:
			subline ??
			props.X08wkFYiN ??
			"Jumping between platforms for videos quizzes emails and files breaks your flow every day.",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		AI2SJBoqv: AI2SJBoqv2,
		X08wkFYiN: X08wkFYiN2,
		j6FrGQEgK: j6FrGQEgK2,
		feFxhFHQx: feFxhFHQx2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "ez7OSsTNr",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "S8hi1XwTG") return true;
		return false;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "WXVIZlnuV") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1f6l56w",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Single"}
						layoutDependency={layoutDependency}
						layoutId={"ez7OSsTNr"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "2px",
							"--border-color":
								"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
							"--border-left-width": "2px",
							"--border-right-width": "2px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							backgroundColor: feFxhFHQx2,
							boxShadow:
								"8px 8px 0px 0px var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								Qfwu_ux6i: {
									"data-framer-name": "Double - Mobile",
								},
								S8hi1XwTG: {
									"data-framer-name": "problem-card",
								},
								WXVIZlnuV: {
									"data-framer-name": "Double",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-9vsty4"}
							data-framer-name={"wrapper"}
							layoutDependency={layoutDependency}
							layoutId={"T5IxTejKz"}
						>
							{isDisplayed() && (
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 1e3,
										intrinsicWidth: 1e3,
										pixelHeight: 2e3,
										pixelWidth: 2e3,
										src: "https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?width=2000&height=2000",
										srcSet:
											"https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?scale-down-to=512&width=2000&height=2000 512w,https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?scale-down-to=1024&width=2000&height=2000 1024w,https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?width=2000&height=2000 2000w",
									}}
									className={"framer-1au8zdp"}
									data-framer-name={"Untitled design"}
									layoutDependency={layoutDependency}
									layoutId={"QWzPxNhCX"}
									{...addPropertyOverrides(
										{
											S8hi1XwTG: {
												background: {
													alt: "",
													fit: "fill",
													intrinsicHeight: 1e3,
													intrinsicWidth: 1e3,
													loading: getLoadingLazyAtYPosition(
														(componentViewport?.y || 0) + 0 + 20 + 0,
													),
													pixelHeight: 2e3,
													pixelWidth: 2e3,
													sizes: "40px",
													src: "https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?width=2000&height=2000",
													srcSet:
														"https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?scale-down-to=512&width=2000&height=2000 512w,https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?scale-down-to=1024&width=2000&height=2000 1024w,https://framerusercontent.com/images/DHBR4kTh0Cix8xWCRIMk7Aplds.png?width=2000&height=2000 2000w",
												},
											},
										},
										baseVariant,
										gestureVariant,
									)}
								/>
							)}
							<motion.div
								className={"framer-39127p"}
								data-framer-name={"wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"hZWCJA6BG"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-o0077q"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ez7OSsTNrpBhieykVM"}
									style={{
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={AI2SJBoqv2}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											S8hi1XwTG: {
												children: (
													<React.Fragment>
														<motion.h3
															className={"framer-styles-preset-1w6sc1n"}
															data-styles-preset={"WCABqTCb2"}
															style={{
																"--framer-text-alignment": "center",
															}}
														>
															{"Too many tools to handle"}
														</motion.h3>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.h3
											className={"framer-styles-preset-1w6sc1n"}
											data-styles-preset={"WCABqTCb2"}
											style={{
												"--framer-text-alignment": "left",
											}}
										>
											{"Too many tools to handle"}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-utlwrm"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ez7OSsTNrcj6Ja9URz"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={X08wkFYiN2}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											S8hi1XwTG: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-1wx5uu0"}
															data-styles-preset={"yWUJk0B4D"}
															dir={"auto"}
															style={{
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
															}}
														>
															{
																"Jumping between platforms for videos quizzes emails and files breaks your flow every day."
															}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1wx5uu0"}
											data-styles-preset={"yWUJk0B4D"}
											dir={"auto"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0)))",
											}}
										>
											{
												"Jumping between platforms for videos quizzes emails and files breaks your flow every day."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						{isDisplayed1() && (
							<Image
								background={{
									alt: "",
									fit: "fill",
									...toResponsiveImage(j6FrGQEgK2),
									...{
										positionX: "left",
										positionY: "center",
									},
								}}
								className={"framer-iyuun0"}
								data-framer-name={"wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"gHG9sh2iQ"}
								{...addPropertyOverrides(
									{
										WXVIZlnuV: {
											background: {
												alt: "",
												fit: "fit",
												loading: getLoadingLazyAtYPosition(
													(componentViewport?.y || 0) + 0,
												),
												sizes: `max(${componentViewport?.width || "100vw"} / 2, 1px)`,
												...toResponsiveImage(j6FrGQEgK2),
												...{
													positionX: "left",
													positionY: "center",
												},
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-CAKEG.framer-1pvff5p, .framer-CAKEG .framer-1pvff5p { display: block; }",
	".framer-CAKEG.framer-1f6l56w { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 350px; }",
	".framer-CAKEG .framer-9vsty4 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: visible; padding: 40px; position: relative; width: 1px; }",
	".framer-CAKEG .framer-1au8zdp { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 1px); overflow: visible; position: relative; width: 40px; }",
	".framer-CAKEG .framer-39127p { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-CAKEG .framer-o0077q { --framer-text-wrap-override: balance; flex: none; height: auto; position: relative; width: 100%; }",
	".framer-CAKEG .framer-utlwrm { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-CAKEG .framer-iyuun0 { align-content: center; align-items: center; align-self: stretch; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 20px; height: auto; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-CAKEG.framer-v-1uq5497.framer-1f6l56w { gap: 0px; width: 700px; }",
	".framer-CAKEG.framer-v-1uq5497 .framer-9vsty4 { align-content: flex-start; align-items: flex-start; }",
	".framer-CAKEG.framer-v-mc29v3.framer-1f6l56w { flex-direction: column; gap: 0px; width: 500px; }",
	".framer-CAKEG.framer-v-mc29v3 .framer-9vsty4 { align-content: flex-start; align-items: flex-start; flex: none; width: 100%; }",
	".framer-CAKEG.framer-v-1h7jz2a .framer-9vsty4 { padding: 20px; }",
	".framer-CAKEG.framer-v-1h7jz2a .framer-1au8zdp { height: var(--framer-aspect-ratio-supported, 40px); order: 0; }",
	".framer-CAKEG.framer-v-1h7jz2a .framer-39127p { order: 1; }",
	...css2,
	...css,
	'.framer-CAKEG[data-border="true"]::after, .framer-CAKEG [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerZp4iwkAsa = withCSS(Component, css3, "framer-CAKEG");
var stdin_default = FramerZp4iwkAsa;
FramerZp4iwkAsa.displayName = "Features Card";
FramerZp4iwkAsa.defaultProps = {
	height: 239,
	width: 350,
};
addPropertyControls(FramerZp4iwkAsa, {
	variant: {
		options: ["ez7OSsTNr", "WXVIZlnuV", "Qfwu_ux6i", "S8hi1XwTG"],
		optionTitles: ["Single", "Double", "Double - Mobile", "problem-card"],
		title: "Variant",
		type: ControlType.Enum,
	},
	AI2SJBoqv: {
		defaultValue: "Too many tools to handle",
		displayTextArea: false,
		title: "Headline",
		type: ControlType.String,
	},
	X08wkFYiN: {
		defaultValue:
			"Jumping between platforms for videos quizzes emails and files breaks your flow every day.",
		displayTextArea: false,
		title: "Subline",
		type: ControlType.String,
	},
	j6FrGQEgK: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	feFxhFHQx: {
		defaultValue:
			'var(--token-735d697b-5a03-49fe-9b66-80e6a14713f9, rgb(255, 255, 255)) /* {"name":"white"} */',
		title: "Background",
		type: ControlType.Color,
	},
});
addFonts(
	FramerZp4iwkAsa,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:features-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale = "", ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FeaturesCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var features_card_default = ComponentWithRoot;
export { features_card_default as default };
