// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-S6ZR3ZZF.js";
import { stdin_default } from "./chunks/chunk-PBFQBE6N.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-LY4LQ73V.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-265SXJWQ.js";
import { routes } from "./chunks/chunk-VG7AXKTA.js";

// virtual:footer
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/kA4ad4MRpOEVrqkR3yv9/Fz56VXx5hUhkpzCMBe2D/SGCpyHKsq.js
import { jsx as _jsx5, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls5,
	ComponentViewportProvider,
	ControlType as ControlType5,
	cx as cx4,
	forwardLoader,
	getFonts,
	ResolveLinks,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS as withCSS4,
} from "unframer";
import { LayoutGroup, motion as motion4, MotionConfigContext } from "unframer";
import * as React4 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/6Vi3NZDhQ2KfYG8IKZoz/NP2oUdZbW2GtyRAnOeDa/ShqULyR1Z.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = `url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 22 0.01 C 21.042 0.686 19.982 1.202 18.86 1.54 C 17.626 0.122 15.638 -0.376 13.882 0.295 C 12.126 0.965 10.975 2.661 11 4.54 L 11 5.54 C 7.431 5.633 4.052 3.932 2 1.01 C 2 1.01 -2 10.01 7 14.01 C 4.941 15.408 2.487 16.109 0 16.01 C 9 21.01 20 16.01 20 4.51 C 19.999 4.232 19.972 3.954 19.92 3.68 C 20.941 2.674 21.661 1.403 22 0.01 Z" fill="transparent" height="17.943889096178417px" id="suKqYRBB0" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(1 2.99)" width="22px"/></svg>') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)`;
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ height, id, stroke, width, ...props }) => {
	return {
		...props,
		UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { style, className, layoutId, variant, UO5clYVeQ, ...restProps } =
		getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-0CHoi", className)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--43q7um": UO5clYVeQ,
				...style,
			}}
		/>
	);
});
var css = [
	`.framer-0CHoi { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css, "framer-0CHoi");
Icon.displayName = "Twitter";
var stdin_default5 = Icon;
addPropertyControls(Icon, {
	UO5clYVeQ: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Stroke",
		type: ControlType.Color,
	},
});

// /:https://framerusercontent.com/modules/DVYtI0I60utFDv4RKjrL/CapkkksUWdCkXmLmQWbV/AutoCopyright_Prod.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
} from "unframer";
var currentYear = /* @__PURE__ */ new Date().getFullYear();
function AutoCopyright(props) {
	const { name, statement, dateRange, startYear, font, color, fontSize } =
		props;
	const yearDisplay = dateRange ? `${startYear}-${currentYear}` : currentYear;
	let displayText = `\xA9 ${yearDisplay} ${name.trim()}`;
	if (statement.trim()) {
		displayText += ` ${statement.trim()}`;
	}
	const textStyle = {
		fontSize: `${fontSize}px`,
		color,
		...font,
	};
	return <div style={textStyle}>{displayText}</div>;
}
AutoCopyright.defaultProps = {
	name: "Your Name",
	statement: "All rights reserved.",
	dateRange: false,
	startYear: currentYear - 1,
	color: "#999999",
	fontSize: 14,
	font: {
		family: "Inter",
	},
};
AutoCopyright.displayName = "Auto Copyright";
addPropertyControls2(AutoCopyright, {
	font: {
		type: ControlType2.Font,
		title: "Font",
		defaultValue: "Inter",
		controls: "extended",
	},
	color: {
		type: ControlType2.Color,
		title: "Color",
		defaultValue: "#999999",
	},
	dateRange: {
		type: ControlType2.Boolean,
		title: "Date Range",
		defaultValue: false,
		enabledTitle: "Yes",
		disabledTitle: "No",
	},
	startYear: {
		type: ControlType2.Number,
		title: "Start Year",
		min: 1e3,
		max: currentYear,
		defaultValue: currentYear - 2,
		displayStepper: true,
		hidden: ({ dateRange }) => !dateRange,
	},
	name: {
		type: ControlType2.String,
		title: "Name",
		defaultValue: "Your Name",
	},
	statement: {
		type: ControlType2.String,
		title: "Statement",
		defaultValue: "All rights reserved.",
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/unXEsZltj7JMvLGo2ocp/yhoQwxi9rSJ8DEYXLcoS/wKjRQ7V57.js
import { jsx as _jsx3 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls3,
	ControlType as ControlType3,
	cx as cx2,
	motion as motion2,
	withCSS as withCSS2,
} from "unframer";
import * as React2 from "react";
import { forwardRef as forwardRef4 } from "react";
var mask2 = `url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 5 20 C 2.239 20 0 17.761 0 15 L 0 5 C 0 2.239 2.239 0 5 0 L 15 0 C 17.761 0 20 2.239 20 5 L 20 15 C 20 17.761 17.761 20 15 20 Z" fill="transparent" height="20px" id="IHmJtUHF2" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(2 2)" width="20px"/><path d="M 7.957 3.413 C 8.21 5.12 7.34 6.797 5.798 7.573 C 4.257 8.349 2.392 8.049 1.172 6.829 C -0.049 5.608 -0.349 3.743 0.427 2.202 C 1.203 0.66 2.88 -0.21 4.587 0.043 C 6.33 0.302 7.698 1.67 7.957 3.413 Z" fill="transparent" height="8.000294809864354px" id="Y3XwIpSTi" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(8.043 7.957)" width="8.000294809864354px"/><path d="M 0 0 L 0.01 0" fill="transparent" height="1px" id="bVuN96Jzj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(17.5 6.5)" width="1px"/></svg>') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)`;
var SVG2 = /* @__PURE__ */ forwardRef4((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion2.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps2 = ({ height, id, stroke, width, ...props }) => {
	return {
		...props,
		UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)",
	};
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const { style, className, layoutId, variant, UO5clYVeQ, ...restProps } =
		getProps2(props);
	return (
		<SVG2
			{...restProps}
			className={cx2("framer-PTgXK", className)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--43q7um": UO5clYVeQ,
				...style,
			}}
		/>
	);
});
var css2 = [
	`.framer-PTgXK { -webkit-mask: ${mask2}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask2}; width: 24px; }`,
];
var Icon2 = withCSS2(Component2, css2, "framer-PTgXK");
Icon2.displayName = "Instagram";
var stdin_default6 = Icon2;
addPropertyControls3(Icon2, {
	UO5clYVeQ: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Stroke",
		type: ControlType3.Color,
	},
});

// /:https://framerusercontent.com/modules/WXrcYwU5ooGmkTpK3FVC/eLrPFzaeIwGyQunnBnz8/B9SzpfZGa.js
import { jsx as _jsx4 } from "react/jsx-runtime";
import {
	addPropertyControls as addPropertyControls4,
	ControlType as ControlType4,
	cx as cx3,
	motion as motion3,
	withCSS as withCSS3,
} from "unframer";
import * as React3 from "react";
import { forwardRef as forwardRef6 } from "react";
var mask3 = `url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 6 0 C 9.314 0 12 2.686 12 6 L 12 13 L 8 13 L 8 6 C 8 4.895 7.105 4 6 4 C 4.895 4 4 4.895 4 6 L 4 13 L 0 13 L 0 6 C 0 2.686 2.686 0 6 0 Z" fill="transparent" height="13px" id="bRR84mvMX" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(10 8)" width="12px"/><path d="M 0 12 L 0 0 L 4 0 L 4 12 Z" fill="transparent" height="12px" id="M4J08UOXj" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(2 9)" width="4px"/><path d="M 0 2 C 0 0.895 0.895 0 2 0 C 3.105 0 4 0.895 4 2 C 4 3.105 3.105 4 2 4 C 0.895 4 0 3.105 0 2 Z" fill="transparent" height="4px" id="CeIp4Vj9i" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" stroke="var(--43q7um, rgb(0,0,0))" transform="translate(2 2)" width="4px"/></svg>') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)`;
var SVG3 = /* @__PURE__ */ forwardRef6((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion3.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps3 = ({ height, id, stroke, width, ...props }) => {
	return {
		...props,
		UO5clYVeQ: stroke ?? props.UO5clYVeQ ?? "rgb(0, 0, 0)",
	};
};
var Component3 = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const { style, className, layoutId, variant, UO5clYVeQ, ...restProps } =
		getProps3(props);
	return (
		<SVG3
			{...restProps}
			className={cx3("framer-YB3QI", className)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--43q7um": UO5clYVeQ,
				...style,
			}}
		/>
	);
});
var css3 = [
	`.framer-YB3QI { -webkit-mask: ${mask3}; aspect-ratio: 1; background-color: var(--43q7um); mask: ${mask3}; width: 24px; }`,
];
var Icon3 = withCSS3(Component3, css3, "framer-YB3QI");
Icon3.displayName = "Linkedin";
var stdin_default7 = Icon3;
addPropertyControls4(Icon3, {
	UO5clYVeQ: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Stroke",
		type: ControlType4.Color,
	},
});

// /:https://framerusercontent.com/modules/kA4ad4MRpOEVrqkR3yv9/Fz56VXx5hUhkpzCMBe2D/SGCpyHKsq.js
var PatternFonts = getFonts(stdin_default);
var BrandLogoFonts = getFonts(stdin_default3);
var NavigationLinkFonts = getFonts(stdin_default2);
var SocialIconFonts = getFonts(stdin_default4);
var AutoCopyrightFonts = getFonts(AutoCopyright);
var cycleOrder = ["fipP2lRkk", "M8acZJfi8", "B4ogt14y_"];
var serializationHash = "framer-WFhDi";
var variantClassNames = {
	B4ogt14y_: "framer-v-sjbp6v",
	fipP2lRkk: "framer-v-1fiw38h",
	M8acZJfi8: "framer-v-vbzviq",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var Transition = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Desktop: "fipP2lRkk",
	Phone: "B4ogt14y_",
	Tablet: "M8acZJfi8",
};
var Variants = motion4.create(React4.Fragment);
var getProps4 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "fipP2lRkk",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component4 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } =
		getProps4(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "fipP2lRkk",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx4(serializationHash, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion4.footer
						{...restProps}
						{...gestureHandlers}
						className={cx4(
							scopingClassNames,
							"framer-1fiw38h",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"fipP2lRkk"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "0px",
							"--border-color":
								"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
							"--border-left-width": "0px",
							"--border-right-width": "0px",
							"--border-style": "solid",
							"--border-top-width": "2px",
							backgroundColor: "rgba(50, 172, 166, 0.3)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								B4ogt14y_: {
									"data-framer-name": "Phone",
								},
								M8acZJfi8: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={(componentViewport?.height || 200) * 1}
							width={componentViewport?.width || "100vw"}
							y={(componentViewport?.y || 0) + 0}
						>
							<SmartComponentScopedContainer
								className={"framer-fmma8r-container"}
								layoutDependency={layoutDependency}
								layoutId={"CdenRaJW0-container"}
								nodeId={"CdenRaJW0"}
								rendersWithMotion={true}
								scopeId={"SGCpyHKsq"}
							>
								{_jsx5(stdin_default, {
									height: "100%",
									id: "CdenRaJW0",
									layoutId: "CdenRaJW0",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion4.div
							className={"framer-141wd44"}
							data-framer-name={"content"}
							layoutDependency={layoutDependency}
							layoutId={"qkM8sfeh8"}
						>
							<motion4.div
								className={"framer-1tunhh0"}
								data-framer-name={"wrapper"}
								layoutDependency={layoutDependency}
								layoutId={"EJF8caQfX"}
							>
								<motion4.div
									className={"framer-7e9on0"}
									data-framer-name={"wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"i9uhjgScL"}
								>
									<ComponentViewportProvider
										height={35}
										y={
											(componentViewport?.y || 0) +
											40 +
											(((componentViewport?.height || 200) - 80 - 305) / 2 +
												0 +
												0) +
											0 +
											0 +
											0 +
											0 +
											5
										}
										{...addPropertyOverrides(
											{
												B4ogt14y_: {
													y:
														(componentViewport?.y || 0) +
														40 +
														(((componentViewport?.height || 200) - 80 - 527) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
												M8acZJfi8: {
													y:
														(componentViewport?.y || 0) +
														40 +
														(((componentViewport?.height || 200) - 80 - 432) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SmartComponentScopedContainer
											className={"framer-q6rtdg-container"}
											layoutDependency={layoutDependency}
											layoutId={"tNKcNQZ3q-container"}
											nodeId={"tNKcNQZ3q"}
											rendersWithMotion={true}
											scopeId={"SGCpyHKsq"}
										>
											{_jsx5(stdin_default3, {
												height: "100%",
												id: "tNKcNQZ3q",
												layoutId: "tNKcNQZ3q",
												oh07xLYVa: addImageAlt(
													{
														pixelHeight: 2e3,
														pixelWidth: 2e3,
														src: "https://framerusercontent.com/images/KPxYlmS5V982pd3qOeQNJ8NPM0w.png?width=2000&height=2000",
														srcSet:
															"https://framerusercontent.com/images/KPxYlmS5V982pd3qOeQNJ8NPM0w.png?scale-down-to=512&width=2000&height=2000 512w,https://framerusercontent.com/images/KPxYlmS5V982pd3qOeQNJ8NPM0w.png?scale-down-to=1024&width=2000&height=2000 1024w,https://framerusercontent.com/images/KPxYlmS5V982pd3qOeQNJ8NPM0w.png?width=2000&height=2000 2000w",
													},
													"",
												),
												tWKd7erWt: addImageAlt(
													{
														pixelHeight: 1950,
														pixelWidth: 5630,
														src: "https://framerusercontent.com/images/poYwCEJ7PbKUEZffe5cE5tU5LK0.png?width=5630&height=1950",
														srcSet:
															"https://framerusercontent.com/images/poYwCEJ7PbKUEZffe5cE5tU5LK0.png?scale-down-to=512&width=5630&height=1950 512w,https://framerusercontent.com/images/poYwCEJ7PbKUEZffe5cE5tU5LK0.png?scale-down-to=1024&width=5630&height=1950 1024w,https://framerusercontent.com/images/poYwCEJ7PbKUEZffe5cE5tU5LK0.png?scale-down-to=2048&width=5630&height=1950 2048w,https://framerusercontent.com/images/poYwCEJ7PbKUEZffe5cE5tU5LK0.png?scale-down-to=4096&width=5630&height=1950 4096w,https://framerusercontent.com/images/poYwCEJ7PbKUEZffe5cE5tU5LK0.png?width=5630&height=1950 5630w",
													},
													"",
												),
												variant: matchVariant("rAAOarYyf"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
									<motion4.nav
										className={"framer-147uxrv"}
										data-framer-name={"nav"}
										layoutDependency={layoutDependency}
										layoutId={"UVYWIBWVv"}
									>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":jxRb7HA2A",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":jxRb7HA2A",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":jxRb7HA2A",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks) => (
												<ComponentViewportProvider
													height={45}
													y={
														(componentViewport?.y || 0) +
														40 +
														(((componentViewport?.height || 200) - 80 - 305) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															B4ogt14y_: {
																width: `min(${componentViewport?.width || "100vw"} - 40px, 1200px)`,
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		527) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	55 +
																	0 +
																	0,
															},
															M8acZJfi8: {
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		432) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	75 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-d1gw5e-container"}
														layoutDependency={layoutDependency}
														layoutId={"ZFEDWuAng-container"}
														nodeId={"ZFEDWuAng"}
														rendersWithMotion={true}
														scopeId={"SGCpyHKsq"}
													>
														{_jsx5(stdin_default2, {
															height: "100%",
															id: "ZFEDWuAng",
															J4dY5fj3I: "Features",
															layoutId: "ZFEDWuAng",
															LNDVh1koq: resolvedLinks[0],
															UmLY9rSFi: false,
															width: "100%",
															...addPropertyOverrides(
																{
																	B4ogt14y_: {
																		LNDVh1koq: resolvedLinks[2],
																		style: {
																			width: "100%",
																		},
																	},
																	M8acZJfi8: {
																		LNDVh1koq: resolvedLinks[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":UeW2rucFy",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":UeW2rucFy",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":bmCL3S8v7",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks1) => (
												<ComponentViewportProvider
													height={45}
													y={
														(componentViewport?.y || 0) +
														40 +
														(((componentViewport?.height || 200) - 80 - 305) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															B4ogt14y_: {
																width: `min(${componentViewport?.width || "100vw"} - 40px, 1200px)`,
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		527) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	55 +
																	0 +
																	45,
															},
															M8acZJfi8: {
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		432) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	75 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-1c2m1qn-container"}
														layoutDependency={layoutDependency}
														layoutId={"xXda_BVq6-container"}
														nodeId={"xXda_BVq6"}
														rendersWithMotion={true}
														scopeId={"SGCpyHKsq"}
													>
														{_jsx5(stdin_default2, {
															height: "100%",
															id: "xXda_BVq6",
															J4dY5fj3I: "How it works",
															layoutId: "xXda_BVq6",
															LNDVh1koq: resolvedLinks1[0],
															UmLY9rSFi: false,
															width: "100%",
															...addPropertyOverrides(
																{
																	B4ogt14y_: {
																		LNDVh1koq: resolvedLinks1[2],
																		style: {
																			width: "100%",
																		},
																	},
																	M8acZJfi8: {
																		LNDVh1koq: resolvedLinks1[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														hash: ":woRj94GG4",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":woRj94GG4",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														hash: ":woRj94GG4",
														webPageId: "augiA20Il",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks2) => (
												<ComponentViewportProvider
													height={45}
													y={
														(componentViewport?.y || 0) +
														40 +
														(((componentViewport?.height || 200) - 80 - 305) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															B4ogt14y_: {
																width: `min(${componentViewport?.width || "100vw"} - 40px, 1200px)`,
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		527) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	55 +
																	0 +
																	90,
															},
															M8acZJfi8: {
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		432) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	75 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-1fks8hk-container"}
														layoutDependency={layoutDependency}
														layoutId={"vFyTvfshs-container"}
														nodeId={"vFyTvfshs"}
														rendersWithMotion={true}
														scopeId={"SGCpyHKsq"}
													>
														{_jsx5(stdin_default2, {
															height: "100%",
															id: "vFyTvfshs",
															J4dY5fj3I: "FAQ",
															layoutId: "vFyTvfshs",
															LNDVh1koq: resolvedLinks2[0],
															UmLY9rSFi: false,
															width: "100%",
															...addPropertyOverrides(
																{
																	B4ogt14y_: {
																		LNDVh1koq: resolvedLinks2[2],
																		style: {
																			width: "100%",
																		},
																	},
																	M8acZJfi8: {
																		LNDVh1koq: resolvedLinks2[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
										<ResolveLinks
											links={[
												{
													href: {
														webPageId: "CAx42JOO2",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "CAx42JOO2",
													},
													implicitPathVariables: void 0,
												},
												{
													href: {
														webPageId: "CAx42JOO2",
													},
													implicitPathVariables: void 0,
												},
											]}
										>
											{(resolvedLinks3) => (
												<ComponentViewportProvider
													height={45}
													y={
														(componentViewport?.y || 0) +
														40 +
														(((componentViewport?.height || 200) - 80 - 305) /
															2 +
															0 +
															0) +
														0 +
														0 +
														0 +
														0 +
														0 +
														0
													}
													{...addPropertyOverrides(
														{
															B4ogt14y_: {
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		527) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	55 +
																	0 +
																	135,
															},
															M8acZJfi8: {
																y:
																	(componentViewport?.y || 0) +
																	40 +
																	(((componentViewport?.height || 200) -
																		80 -
																		432) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0 +
																	0 +
																	0 +
																	0 +
																	75 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-lf0af2-container"}
														layoutDependency={layoutDependency}
														layoutId={"uMQzSRLNS-container"}
														nodeId={"uMQzSRLNS"}
														rendersWithMotion={true}
														scopeId={"SGCpyHKsq"}
													>
														{_jsx5(stdin_default2, {
															height: "100%",
															id: "uMQzSRLNS",
															J4dY5fj3I: "Log In",
															layoutId: "uMQzSRLNS",
															LNDVh1koq: resolvedLinks3[0],
															UmLY9rSFi: false,
															width: "100%",
															...addPropertyOverrides(
																{
																	B4ogt14y_: {
																		LNDVh1koq: resolvedLinks3[2],
																	},
																	M8acZJfi8: {
																		LNDVh1koq: resolvedLinks3[1],
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											)}
										</ResolveLinks>
									</motion4.nav>
									<motion4.nav
										className={"framer-1eohvnv"}
										data-framer-name={"nav"}
										layoutDependency={layoutDependency}
										layoutId={"jS_ZlqoDc"}
									>
										<ComponentViewportProvider
											height={32}
											y={
												(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 200) - 80 - 305) / 2 +
													0 +
													0) +
												0 +
												0 +
												0 +
												0 +
												6.5 +
												0
											}
											{...addPropertyOverrides(
												{
													B4ogt14y_: {
														y:
															(componentViewport?.y || 0) +
															40 +
															(((componentViewport?.height || 200) - 80 - 527) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															255 +
															0,
													},
													M8acZJfi8: {
														y:
															(componentViewport?.y || 0) +
															40 +
															(((componentViewport?.height || 200) - 80 - 432) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															160 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-18009wy-container"}
												layoutDependency={layoutDependency}
												layoutId={"tRdUF3FAH-container"}
												nodeId={"tRdUF3FAH"}
												rendersWithMotion={true}
												scopeId={"SGCpyHKsq"}
											>
												{_jsx5(stdin_default4, {
													cJ_x9H3iS: true,
													height: "100%",
													id: "tRdUF3FAH",
													layoutId: "tRdUF3FAH",
													RHe7FUdR_: stdin_default6,
													width: "100%",
													Ye2PVKAEQ: "https://www.facebook.com/",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={32}
											y={
												(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 200) - 80 - 305) / 2 +
													0 +
													0) +
												0 +
												0 +
												0 +
												0 +
												6.5 +
												0
											}
											{...addPropertyOverrides(
												{
													B4ogt14y_: {
														y:
															(componentViewport?.y || 0) +
															40 +
															(((componentViewport?.height || 200) - 80 - 527) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															255 +
															0,
													},
													M8acZJfi8: {
														y:
															(componentViewport?.y || 0) +
															40 +
															(((componentViewport?.height || 200) - 80 - 432) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															160 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1aqrixi-container"}
												layoutDependency={layoutDependency}
												layoutId={"yprjevzjo-container"}
												nodeId={"yprjevzjo"}
												rendersWithMotion={true}
												scopeId={"SGCpyHKsq"}
											>
												{_jsx5(stdin_default4, {
													cJ_x9H3iS: true,
													height: "100%",
													id: "yprjevzjo",
													layoutId: "yprjevzjo",
													RHe7FUdR_: stdin_default5,
													width: "100%",
													Ye2PVKAEQ: "https://www.instagram.com/",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
										<ComponentViewportProvider
											height={32}
											y={
												(componentViewport?.y || 0) +
												40 +
												(((componentViewport?.height || 200) - 80 - 305) / 2 +
													0 +
													0) +
												0 +
												0 +
												0 +
												0 +
												6.5 +
												0
											}
											{...addPropertyOverrides(
												{
													B4ogt14y_: {
														y:
															(componentViewport?.y || 0) +
															40 +
															(((componentViewport?.height || 200) - 80 - 527) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															255 +
															0,
													},
													M8acZJfi8: {
														y:
															(componentViewport?.y || 0) +
															40 +
															(((componentViewport?.height || 200) - 80 - 432) /
																2 +
																0 +
																0) +
															0 +
															0 +
															0 +
															0 +
															0 +
															160 +
															0,
													},
												},
												baseVariant,
												gestureVariant,
											)}
										>
											<SmartComponentScopedContainer
												className={"framer-1kznimv-container"}
												layoutDependency={layoutDependency}
												layoutId={"N6lJXRssl-container"}
												nodeId={"N6lJXRssl"}
												rendersWithMotion={true}
												scopeId={"SGCpyHKsq"}
											>
												{_jsx5(stdin_default4, {
													cJ_x9H3iS: true,
													height: "100%",
													id: "N6lJXRssl",
													layoutId: "N6lJXRssl",
													RHe7FUdR_: stdin_default7,
													width: "100%",
													Ye2PVKAEQ: "https://www.snapchat.com/",
												})}
											</SmartComponentScopedContainer>
										</ComponentViewportProvider>
									</motion4.nav>
								</motion4.div>
								<motion4.div
									className={"framer-18wsnj8"}
									data-framer-name={"wrapper"}
									layoutDependency={layoutDependency}
									layoutId={"AnS4WBFcZ"}
								>
									<ComponentViewportProvider>
										<SmartComponentScopedContainer
											className={"framer-17prp9w-container"}
											isAuthoredByUser={true}
											isModuleExternal={true}
											layoutDependency={layoutDependency}
											layoutId={"IA7cbrME3-container"}
											nodeId={"IA7cbrME3"}
											rendersWithMotion={true}
											scopeId={"SGCpyHKsq"}
										>
											<AutoCopyright
												color={
													"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))"
												}
												dateRange={false}
												font={{
													fontFamily:
														'"Epilogue", "Epilogue Placeholder", sans-serif',
													fontSize: "14px",
													fontStyle: "normal",
													fontWeight: 500,
													letterSpacing: "-0.04em",
													lineHeight: "1.5em",
												}}
												height={"100%"}
												id={"IA7cbrME3"}
												layoutId={"IA7cbrME3"}
												name={"Built by a CWRU student \u{1F420}"}
												startYear={2024}
												statement={""}
												width={"100%"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								</motion4.div>
							</motion4.div>
						</motion4.div>
					</motion4.footer>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WFhDi.framer-8x72om, .framer-WFhDi .framer-8x72om { display: block; }",
	".framer-WFhDi.framer-1fiw38h { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 40px; position: relative; width: 1200px; }",
	".framer-WFhDi .framer-fmma8r-container { flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; top: 0px; width: 100%; z-index: 0; }",
	".framer-WFhDi .framer-141wd44 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 100px; height: min-content; justify-content: center; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-WFhDi .framer-1tunhh0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 60px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-WFhDi .framer-7e9on0 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-WFhDi .framer-q6rtdg-container, .framer-WFhDi .framer-d1gw5e-container, .framer-WFhDi .framer-1c2m1qn-container, .framer-WFhDi .framer-1fks8hk-container, .framer-WFhDi .framer-lf0af2-container, .framer-WFhDi .framer-18009wy-container, .framer-WFhDi .framer-1aqrixi-container, .framer-WFhDi .framer-1kznimv-container, .framer-WFhDi .framer-17prp9w-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-WFhDi .framer-147uxrv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-WFhDi .framer-1eohvnv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: min-content; }",
	".framer-WFhDi .framer-18wsnj8 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 12px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 100%; }",
	".framer-WFhDi.framer-v-vbzviq.framer-1fiw38h { width: 810px; }",
	".framer-WFhDi.framer-v-vbzviq .framer-1tunhh0, .framer-WFhDi.framer-v-sjbp6v .framer-1tunhh0 { gap: 40px; }",
	".framer-WFhDi.framer-v-vbzviq .framer-7e9on0 { flex-direction: column; gap: 40px; justify-content: flex-start; }",
	".framer-WFhDi.framer-v-vbzviq .framer-q6rtdg-container { order: 0; }",
	".framer-WFhDi.framer-v-vbzviq .framer-147uxrv { order: 1; }",
	".framer-WFhDi.framer-v-vbzviq .framer-1eohvnv { order: 2; }",
	".framer-WFhDi.framer-v-sjbp6v.framer-1fiw38h { padding: 40px 20px 40px 20px; width: 390px; }",
	".framer-WFhDi.framer-v-sjbp6v .framer-7e9on0 { flex-direction: column; gap: 20px; justify-content: flex-start; }",
	".framer-WFhDi.framer-v-sjbp6v .framer-147uxrv { flex-direction: column; width: 100%; }",
	".framer-WFhDi.framer-v-sjbp6v .framer-d1gw5e-container, .framer-WFhDi.framer-v-sjbp6v .framer-1c2m1qn-container, .framer-WFhDi.framer-v-sjbp6v .framer-1fks8hk-container { width: 100%; }",
	'.framer-WFhDi[data-border="true"]::after, .framer-WFhDi [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerSGCpyHKsq = withCSS4(Component4, css4, "framer-WFhDi");
var stdin_default8 = FramerSGCpyHKsq;
FramerSGCpyHKsq.displayName = "Footer";
FramerSGCpyHKsq.defaultProps = {
	height: 206,
	width: 1200,
};
addPropertyControls5(FramerSGCpyHKsq, {
	variant: {
		options: ["fipP2lRkk", "M8acZJfi8", "B4ogt14y_"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType5.Enum,
	},
});
addFonts(
	FramerSGCpyHKsq,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Epilogue",
					source: "fontshare",
					style: "normal",
					uiFamilyName: "Epilogue",
					url: "https://framerusercontent.com/third-party-assets/fontshare/wf/WDPE67UE6MLVKZVLWNP7I6K4BJNXYM75/MEDFVVGRWXNVGRX77CSMLVJYEDA7HC6N/ZCQFQWYK27HETQBG4QFK4TEYPCJZ4KXY.woff2",
					weight: "500",
				},
			],
		},
		...PatternFonts,
		...BrandLogoFonts,
		...NavigationLinkFonts,
		...SocialIconFonts,
		...AutoCopyrightFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
FramerSGCpyHKsq.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([
			forwardLoader(stdin_default, {}, context),
			forwardLoader(stdin_default3, {}, context),
			forwardLoader(stdin_default2, {}, context),
			forwardLoader(stdin_default4, {}, context),
		]);
	},
};

// virtual:footer
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default8, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders FooterFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default8}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default8);
var footer_default = ComponentWithRoot;
export { footer_default as default };
