// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project  "undefined", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Phone' // Variant
}} Props

 */
import { stdin_default as stdin_default4 } from "./chunks/chunk-KUO36J2R.js";
import { stdin_default as stdin_default3 } from "./chunks/chunk-GUJIID4K.js";
import { stdin_default } from "./chunks/chunk-PBFQBE6N.js";
import "./chunks/chunk-DNUIZVT6.js";
import "./chunks/chunk-MMET2FZU.js";
import "./chunks/chunk-H3CR5NCT.js";
import "./chunks/chunk-LY4LQ73V.js";
import { stdin_default as stdin_default2 } from "./chunks/chunk-265SXJWQ.js";
import { routes } from "./chunks/chunk-VG7AXKTA.js";

// virtual:header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/uqBuSVWlZxlXrnY8DPDG/qQeD1xLIdWy0w3qMq7hO/Vh_CHVFOf.js
import {
	jsx as _jsx,
	jsxs as _jsxs,
	Fragment as _Fragment,
} from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	Floating,
	getFonts,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOverlayState,
	useVariantState,
	withCSS,
	withFX,
} from "unframer";
import {
	AnimatePresence,
	LayoutGroup,
	motion,
	MotionConfigContext,
} from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";
var PatternFonts = getFonts(stdin_default);
var BrandLogoFonts = getFonts(stdin_default2);
var NavigationFonts = getFonts(stdin_default3);
var HamburgerMenuFonts = getFonts(stdin_default4);
var MotionNavWithFX = withFX(motion.nav);
var cycleOrder = ["dl_JZJH5Z", "C_M_QsHrR", "fKtCkPJny"];
var serializationHash = "framer-gZV5f";
var variantClassNames = {
	C_M_QsHrR: "framer-v-110pe11",
	dl_JZJH5Z: "framer-v-aw0er6",
	fKtCkPJny: "framer-v-p1tt9b",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var addImageAlt = (image, alt) => {
	if (!image || typeof image !== "object") {
		return;
	}
	return {
		...image,
		alt,
	};
};
var matchVariant = (...args) => {
	for (const arg of args) {
		if (arg && typeof arg === "string") return arg;
	}
	return void 0;
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition1,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 0,
};
var Overlay = ({
	children,
	blockDocumentScrolling,
	dismissWithEsc,
	enabled = true,
}) => {
	const [visible, setVisible] = useOverlayState({
		blockDocumentScrolling,
		dismissWithEsc: enabled && dismissWithEsc,
	});
	return children({
		hide: () => setVisible(false),
		show: () => setVisible(true),
		toggle: () => setVisible(!visible),
		visible: enabled && visible,
	});
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Desktop: "dl_JZJH5Z",
	Phone: "fKtCkPJny",
	Tablet: "C_M_QsHrR",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "dl_JZJH5Z",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "dl_JZJH5Z",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const t2NJCCzh34any77 = activeVariantCallback(async (...args) => {
		setVariant("fKtCkPJny");
	});
	const IPKj2KM2A13elrgn = ({ overlay }) =>
		activeVariantCallback(async (...args) => {
			overlay.show();
		});
	const u1HNSfe7w1q29jei = ({ overlay }) =>
		activeVariantCallback(async (...args) => {
			overlay.hide();
		});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["C_M_QsHrR", "fKtCkPJny"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (["C_M_QsHrR", "fKtCkPJny"].includes(baseVariant)) return true;
		return false;
	};
	const ref1 = React.useRef(null);
	const ref2 = React.useRef(null);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.header
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-aw0er6",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"dl_JZJH5Z"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-e27a4cac-2b4d-4ad5-8c68-b6f48982239d, rgb(249, 245, 246))",
							...style,
						}}
						{...addPropertyOverrides(
							{
								C_M_QsHrR: {
									"data-framer-name": "Tablet",
								},
								fKtCkPJny: {
									"data-framer-name": "Phone",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider
							height={(componentViewport?.height || 88) * 1}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								(componentViewport?.height || 88) -
								(0 + (componentViewport?.height || 88) * 1)
							}
						>
							<SmartComponentScopedContainer
								className={"framer-1c8h24p-container"}
								layoutDependency={layoutDependency}
								layoutId={"gkQ0L1pse-container"}
								nodeId={"gkQ0L1pse"}
								rendersWithMotion={true}
								scopeId={"Vh_CHVFOf"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "gkQ0L1pse",
									layoutId: "gkQ0L1pse",
									style: {
										height: "100%",
										width: "100%",
									},
									width: "100%",
								})}
							</SmartComponentScopedContainer>
						</ComponentViewportProvider>
						<motion.div
							className={"framer-1ubnzhg"}
							data-framer-name={"content"}
							layoutDependency={layoutDependency}
							layoutId={"aQdIdsMKW"}
						>
							<ComponentViewportProvider
								height={48}
								y={
									(componentViewport?.y || 0) +
									20 +
									(((componentViewport?.height || 88) - 40 - 48) / 2 + 0 + 0) +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-x7ouq-container"}
									layoutDependency={layoutDependency}
									layoutId={"l2ear7B8p-container"}
									nodeId={"l2ear7B8p"}
									rendersWithMotion={true}
									scopeId={"Vh_CHVFOf"}
								>
									{_jsx(stdin_default2, {
										height: "100%",
										id: "l2ear7B8p",
										layoutId: "l2ear7B8p",
										oh07xLYVa: addImageAlt(
											{
												pixelHeight: 2e3,
												pixelWidth: 2e3,
												src: "https://framerusercontent.com/images/QVfYzRv9XQaJZ26QhKKD0TMKZA.png?width=2000&height=2000",
												srcSet:
													"https://framerusercontent.com/images/QVfYzRv9XQaJZ26QhKKD0TMKZA.png?scale-down-to=512&width=2000&height=2000 512w,https://framerusercontent.com/images/QVfYzRv9XQaJZ26QhKKD0TMKZA.png?scale-down-to=1024&width=2000&height=2000 1024w,https://framerusercontent.com/images/QVfYzRv9XQaJZ26QhKKD0TMKZA.png?width=2000&height=2000 2000w",
											},
											"",
										),
										style: {
											height: "100%",
										},
										tWKd7erWt: addImageAlt(
											{
												pixelHeight: 1950,
												pixelWidth: 5630,
												src: "https://framerusercontent.com/images/n375GCjfb64K9jJZiBWWifyd9E.png?width=5630&height=1950",
												srcSet:
													"https://framerusercontent.com/images/n375GCjfb64K9jJZiBWWifyd9E.png?scale-down-to=512&width=5630&height=1950 512w,https://framerusercontent.com/images/n375GCjfb64K9jJZiBWWifyd9E.png?scale-down-to=1024&width=5630&height=1950 1024w,https://framerusercontent.com/images/n375GCjfb64K9jJZiBWWifyd9E.png?scale-down-to=2048&width=5630&height=1950 2048w,https://framerusercontent.com/images/n375GCjfb64K9jJZiBWWifyd9E.png?scale-down-to=4096&width=5630&height=1950 4096w,https://framerusercontent.com/images/n375GCjfb64K9jJZiBWWifyd9E.png?width=5630&height=1950 5630w",
											},
											"",
										),
										variant: matchVariant("rAAOarYyf"),
										width: "100%",
										...addPropertyOverrides(
											{
												C_M_QsHrR: {
													variant: matchVariant("LnmgxMA1Z"),
												},
												fKtCkPJny: {
													t2NJCCzh3: t2NJCCzh34any77,
													variant: matchVariant("LnmgxMA1Z"),
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<motion.nav
								className={"framer-1ac0k8v"}
								data-framer-name={"nav"}
								layoutDependency={layoutDependency}
								layoutId={"mkf_bDH5N"}
							>
								{isDisplayed() && (
									<ComponentViewportProvider
										height={48}
										y={
											(componentViewport?.y || 0) +
											20 +
											(((componentViewport?.height || 88) - 40 - 48) / 2 +
												0 +
												0) +
											0 +
											0
										}
									>
										<SmartComponentScopedContainer
											className={"framer-tu2cwp-container"}
											layoutDependency={layoutDependency}
											layoutId={"jPJSmihVE-container"}
											nodeId={"jPJSmihVE"}
											rendersWithMotion={true}
											scopeId={"Vh_CHVFOf"}
										>
											{_jsx(stdin_default3, {
												height: "100%",
												id: "jPJSmihVE",
												layoutId: "jPJSmihVE",
												variant: matchVariant("EyPOrIxne"),
												width: "100%",
											})}
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
								{isDisplayed1() && (
									<Overlay
										blockDocumentScrolling={false}
										dismissWithEsc={false}
									>
										{(overlay) => (
											<_Fragment>
												<ComponentViewportProvider
													{...addPropertyOverrides(
														{
															C_M_QsHrR: {
																height: 48,
																width: "48px",
																y:
																	(componentViewport?.y || 0) +
																	20 +
																	(((componentViewport?.height || 88) -
																		40 -
																		48) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0,
															},
															fKtCkPJny: {
																height: 48,
																width: "48px",
																y:
																	(componentViewport?.y || 0) +
																	20 +
																	(((componentViewport?.height || 88) -
																		40 -
																		48) /
																		2 +
																		0 +
																		0) +
																	0 +
																	0,
															},
														},
														baseVariant,
														gestureVariant,
													)}
												>
													<SmartComponentScopedContainer
														className={"framer-19h0n81-container"}
														id={`${layoutId}-19h0n81`}
														layoutDependency={layoutDependency}
														layoutId={"b2q8o81Y0-container"}
														nodeId={"b2q8o81Y0"}
														ref={ref1}
														rendersWithMotion={true}
														scopeId={"Vh_CHVFOf"}
													>
														{_jsx(stdin_default4, {
															height: "100%",
															id: "b2q8o81Y0",
															IPKj2KM2A: IPKj2KM2A13elrgn({
																overlay,
															}),
															layoutId: "b2q8o81Y0",
															style: {
																height: "100%",
																width: "100%",
															},
															variant: matchVariant(
																overlay.visible && "SeaVIvN9v",
																overlay.visible ? "SeaVIvN9v" : "Yp_wOx8k9",
															),
															width: "100%",
															...addPropertyOverrides(
																{
																	C_M_QsHrR: {
																		variant: matchVariant(
																			overlay.visible && "M_5j3ptep",
																			overlay.visible
																				? "M_5j3ptep"
																				: "Yp_wOx8k9",
																		),
																	},
																	fKtCkPJny: {
																		variant: matchVariant(
																			overlay.visible && "M_5j3ptep",
																			overlay.visible
																				? "M_5j3ptep"
																				: "Yp_wOx8k9",
																		),
																	},
																},
																baseVariant,
																gestureVariant,
															),
														})}
														<AnimatePresence>
															{overlay.visible && (
																<Floating
																	alignment={"end"}
																	anchorRef={ref1}
																	className={cx(scopingClassNames, classNames)}
																	collisionDetection={true}
																	collisionDetectionPadding={20}
																	data-framer-portal-id={`${layoutId}-19h0n81`}
																	offsetX={0}
																	offsetY={30}
																	onDismiss={overlay.hide}
																	placement={"bottom"}
																	safeArea={false}
																	zIndex={11}
																>
																	<MotionNavWithFX
																		__perspectiveFX={false}
																		__smartComponentFX={true}
																		__targetOpacity={1}
																		animate={animation1}
																		className={"framer-1p8ocjd"}
																		data-border={true}
																		exit={animation}
																		initial={animation2}
																		layoutDependency={layoutDependency}
																		layoutId={"focPOvlm4"}
																		ref={ref2}
																		role={"dialog"}
																		style={{
																			"--border-bottom-width": "2px",
																			"--border-color":
																				"var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
																			"--border-left-width": "2px",
																			"--border-right-width": "2px",
																			"--border-style": "solid",
																			"--border-top-width": "2px",
																			backgroundColor:
																				"var(--token-e27a4cac-2b4d-4ad5-8c68-b6f48982239d, rgb(249, 245, 246))",
																			boxShadow:
																				"4px 4px 0px 0px var(--token-14825bd6-f9b4-4846-afef-1af0cbf8c065, rgb(0, 0, 0))",
																		}}
																	>
																		<ComponentViewportProvider width={"176px"}>
																			<SmartComponentScopedContainer
																				className={"framer-1i9qps3-container"}
																				inComponentSlot={true}
																				layoutDependency={layoutDependency}
																				layoutId={"qcg2n0NG7-container"}
																				nodeId={"qcg2n0NG7"}
																				rendersWithMotion={true}
																				scopeId={"Vh_CHVFOf"}
																			>
																				{_jsx(stdin_default3, {
																					height: "100%",
																					id: "qcg2n0NG7",
																					layoutId: "qcg2n0NG7",
																					style: {
																						width: "100%",
																					},
																					variant: matchVariant("xKoXzkzKL"),
																					width: "100%",
																					...addPropertyOverrides(
																						{
																							C_M_QsHrR: {
																								u1HNSfe7w: u1HNSfe7w1q29jei({
																									overlay,
																								}),
																							},
																							fKtCkPJny: {
																								u1HNSfe7w: u1HNSfe7w1q29jei({
																									overlay,
																								}),
																							},
																						},
																						baseVariant,
																						gestureVariant,
																					),
																				})}
																			</SmartComponentScopedContainer>
																		</ComponentViewportProvider>
																	</MotionNavWithFX>
																</Floating>
															)}
														</AnimatePresence>
													</SmartComponentScopedContainer>
												</ComponentViewportProvider>
											</_Fragment>
										)}
									</Overlay>
								)}
							</motion.nav>
						</motion.div>
					</motion.header>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gZV5f.framer-1k0xh8z, .framer-gZV5f .framer-1k0xh8z { display: block; }",
	".framer-gZV5f.framer-aw0er6 { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: hidden; padding: 20px 40px 20px 40px; position: relative; width: 1200px; }",
	".framer-gZV5f .framer-1c8h24p-container { bottom: 0px; flex: none; height: 100%; left: calc(50.00000000000002% - 100% / 2); position: absolute; width: 100%; z-index: 0; }",
	".framer-gZV5f .framer-1ubnzhg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; max-width: 1200px; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-gZV5f .framer-x7ouq-container { align-self: stretch; flex: none; height: auto; position: relative; width: auto; }",
	".framer-gZV5f .framer-1ac0k8v { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: min-content; }",
	".framer-gZV5f .framer-tu2cwp-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-gZV5f .framer-19h0n81-container { flex: none; height: 48px; position: relative; width: 48px; }",
	".framer-gZV5f .framer-1p8ocjd { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 12px; position: relative; width: 200px; }",
	".framer-gZV5f .framer-1i9qps3-container { flex: none; height: auto; position: relative; width: 100%; }",
	".framer-gZV5f.framer-v-110pe11.framer-aw0er6 { width: 810px; }",
	".framer-gZV5f.framer-v-110pe11 .framer-1p8ocjd, .framer-gZV5f.framer-v-p1tt9b .framer-1p8ocjd { -webkit-tap-highlight-color: rgba(0, 0, 0, 0); }",
	".framer-gZV5f.framer-v-p1tt9b.framer-aw0er6 { padding: 20px; width: 390px; }",
	'.framer-gZV5f[data-border="true"]::after, .framer-gZV5f [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerVh_CHVFOf = withCSS(Component, css, "framer-gZV5f");
var stdin_default5 = FramerVh_CHVFOf;
FramerVh_CHVFOf.displayName = "Header";
FramerVh_CHVFOf.defaultProps = {
	height: 88,
	width: 1200,
};
addPropertyControls(FramerVh_CHVFOf, {
	variant: {
		options: ["dl_JZJH5Z", "C_M_QsHrR", "fKtCkPJny"],
		optionTitles: ["Desktop", "Tablet", "Phone"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerVh_CHVFOf,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...PatternFonts,
		...BrandLogoFonts,
		...NavigationFonts,
		...HamburgerMenuFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default5, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={void 0}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default5}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default5);
var header_default = ComponentWithRoot;
export { header_default as default };
